/*
 * Output descriptors, against Electrum's own checksum and BIP-380's.
 *
 * `test/fixtures/descriptors.json` was generated by Electrum's
 * `electrum.descriptor.DescriptorChecksum`, and the finished descriptors were
 * fed back to Electrum's `parse_descriptor`, which read them as WPKH with the
 * origin path `m/84h/0h/0h`. Neither step used any code from this repository.
 *
 * Two anchors in it are stronger than that, because neither Electrum nor this
 * project chose them:
 *
 *   - `raw(deadbeef)#89f8spxm` is the worked example in BIP-380 itself.
 *   - The seed is BIP-39's test vector, so the zpub is BIP-84's published
 *     account key and `73c5da0a` is the master fingerprint every wallet
 *     reports for it. A wrong key origin or a wrong re-serialization shows up
 *     as a mismatch against a number the whole ecosystem agrees on.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import {
  accountXpub,
  bip84Descriptors,
  checksumIsValid,
  descriptorChecksum,
  withChecksum,
} from '../src/keys/descriptor';
import { ZPUB_VERSIONS, openFromMnemonic } from '../src/keys/bitcoin';

const fixture: {
  mnemonic: string;
  zpub: string;
  xpub: string;
  masterFingerprint: number;
  descriptors: { receive: string; change: string; combined: string };
  checksums: { body: string; checksum: string }[];
} = JSON.parse(readFileSync('test/fixtures/descriptors.json', 'utf8'));

describe('the BIP-380 checksum', () => {
  it('agrees with Electrum on every vector, including BIP-380’s own', () => {
    for (const { body, checksum } of fixture.checksums) {
      expect(descriptorChecksum(body), body.slice(0, 40)).toBe(checksum);
    }
    /* Named explicitly so that trimming the fixture cannot quietly remove the
     * one vector that came from the specification rather than from a wallet. */
    expect(descriptorChecksum('raw(deadbeef)')).toBe('89f8spxm');
  });

  it('uses arithmetic wide enough for the generator', () => {
    /* The BCH generator's top constant is 40 bits. JavaScript's bitwise
     * operators are 32-bit and would silently truncate it, producing a
     * checksum that looks like a checksum, differs from everybody else's, and
     * makes every wallet reject the descriptor. There is no way to observe
     * that except by comparing against somebody else, which is what the vector
     * above does — this asserts the property directly so the reason survives. */
    expect(descriptorChecksum('raw(deadbeef)')).not.toBe(descriptorChecksum('raw(deadbeee)'));
  });

  it('refuses a character outside the alphabet rather than skipping it', () => {
    /* Skipping would produce a checksum over a different string than the one
     * being handed out: it would pass its own check and describe other keys. */
    expect(descriptorChecksum('wpkh(xpub…)')).toBeNull();
    expect(withChecksum('raw(deadbeef)ÿ')).toBeNull();
  });

  it('validates one that arrived with a checksum already on it', () => {
    expect(checksumIsValid('raw(deadbeef)#89f8spxm')).toBe(true);
    expect(checksumIsValid('raw(deadbeef)#89f8spxn'), 'a wrong checksum passed').toBe(false);
    expect(checksumIsValid('raw(deadbeef)'), 'a missing checksum passed').toBe(false);
    expect(checksumIsValid('raw(deadbeef)#89f8spx'), 'a short checksum passed').toBe(false);
    expect(checksumIsValid('raw(deadbeef)#89f8spxmm'), 'a long checksum passed').toBe(false);
  });
});

describe('the vault’s own descriptors', () => {
  const wallet = openFromMnemonic(fixture.mnemonic);

  it('starts from the account key the whole ecosystem publishes', () => {
    /* If this drifts, nothing below means anything: the descriptors would be
     * correct descriptions of the wrong wallet. */
    expect(wallet.zpub).toBe(fixture.zpub);
    expect(wallet.masterFingerprint).toBe(fixture.masterFingerprint);
  });

  it('restates the account key as an xpub without changing the key', () => {
    /* A descriptor's `wpkh(...)` already says the script type, so the SLIP-132
     * version bytes would be saying it twice and Bitcoin Core rejects that.
     * Only the four version bytes differ; this is a re-serialization, not a
     * byte edit of a base58 payload. */
    expect(accountXpub(wallet.zpub, ZPUB_VERSIONS)).toBe(fixture.xpub);
    expect(accountXpub('not a key', ZPUB_VERSIONS)).toBeNull();
  });

  it('produces exactly the descriptors Electrum parsed', () => {
    const made = bip84Descriptors(wallet.zpub, ZPUB_VERSIONS, wallet.masterFingerprint);
    expect(made).toEqual(fixture.descriptors);
  });

  it('names the master fingerprint, not the account’s', () => {
    /* The key origin identifies the seed, which is what lets a wallet
     * recognise two accounts as one backup. The account's own fingerprint
     * would work until somebody tried to match two descriptors, and then
     * silently would not. */
    const made = bip84Descriptors(wallet.zpub, ZPUB_VERSIONS, wallet.masterFingerprint)!;
    expect(made.receive).toContain('[73c5da0a/84h/0h/0h]');
    expect(made.receive).not.toContain(`[${(wallet.account.fingerprint >>> 0).toString(16)}/`);
  });

  it('pads a fingerprint whose top bit is set', () => {
    /* `(-1 >>> 0).toString(16)` is eight characters; `(-1).toString(16)` is
     * "-1". A fingerprint above 0x7fffffff is a negative number in
     * JavaScript's signed bit-twiddling, which is half of all seeds. */
    const made = bip84Descriptors(wallet.zpub, ZPUB_VERSIONS, 0xffffffff)!;
    expect(made.receive).toContain('[ffffffff/84h/0h/0h]');
    const small = bip84Descriptors(wallet.zpub, ZPUB_VERSIONS, 0x0000000a)!;
    expect(small.receive).toContain('[0000000a/84h/0h/0h]');
  });

  it('gives receive and change different chains', () => {
    const made = bip84Descriptors(wallet.zpub, ZPUB_VERSIONS, wallet.masterFingerprint)!;
    expect(made.receive).toContain('/0/*)');
    expect(made.change).toContain('/1/*)');
    expect(made.combined).toContain('/<0;1>/*)');
    expect(made.receive).not.toBe(made.change);
  });

  it('says nothing at all for a wallet with no master to name', () => {
    /* A watch-only wallet cannot state a key origin. An origin-less descriptor
     * is legal and is worse than nothing here: it silently drops the fact that
     * makes two accounts recognisable as one seed, and somebody pasting it
     * would never know what they lost. */
    expect(bip84Descriptors(wallet.zpub, ZPUB_VERSIONS, undefined)).toBeNull();
  });

  it('emits single-signature descriptors and has no way to emit any other kind', () => {
    /* The vault does not do multisig, and this is where that would first
     * appear as a half-truth: `wsh(sortedmulti(...))` is a one-line change to
     * write and a very large change to actually support, because multisig
     * means verifying change against a script rather than against a key. */
    /* Comments stripped first. That file's header names `wsh(sortedmulti(…))`
     * in the course of explaining why it will not emit one, which is exactly
     * the sentence a reader needs and exactly the sentence a naive grep
     * mistakes for the thing itself. */
    const code = readFileSync('src/keys/descriptor.ts', 'utf8')
      .split('\n')
      .filter((line) => !/^\s*(\/\/|\*|\/\*)/.test(line))
      .join('\n');
    expect(code).not.toMatch(/sortedmulti|\bmulti\(/);
    const made = bip84Descriptors(wallet.zpub, ZPUB_VERSIONS, wallet.masterFingerprint)!;
    for (const d of Object.values(made)) expect(d.startsWith('wpkh(')).toBe(true);
  });
});
