/**
 * Monero keys, addresses and seed phrases.
 *
 * This is the highest-consequence code on the site. Everything else fails
 * loudly: a wrong GIF looks wrong. A wrong derivation here produces a perfectly
 * valid-looking address that nobody can ever spend from, and there is no way to
 * find out except by losing the money.
 *
 * So the tests are written against things that were not produced by this code:
 * published Keccak vectors, the published ed25519 base point, and a real
 * address generated by the official Monero wallet. Round-trip tests are here
 * too, but they are the weakest kind of evidence — code can round-trip its own
 * mistakes perfectly — so they are never the only check on anything.
 *
 * The one property with no external vector available is private-to-public, and
 * the page says so and tells people to confirm against the official wallet
 * before funding anything. A test file should not pretend to prove more than
 * it does.
 */

import { describe, expect, it } from 'vitest';
import {
  KNOWN_ADDRESS,
  addressChecksum,
  addressFor,
  approximateHeight,
  canWatch,
  allChecksPass,
  base58Decode,
  base58Encode,
  checksumIndex,
  crc32,
  fromHex,
  keysFromSeed,
  mixEntropy,
  mnemonicFromSeed,
  parseAddress,
  publicFromSecret,
  reduceScalar,
  seedFromMnemonic,
  selfTest,
  restoreHeight,
  revealMnemonic,
  revealSecretHex,
  revealWallet,
  toHex,
  wipeWallet,
  watchOnlyExport,
  subaddressFor,
  walletFromMnemonic,
  walletFromSeed,
  type Network,
} from '../src/keys/monero';
import { subaddressKeys } from '../src/keys/monerocrypto';
import { MONERO_WORDS, PREFIX_LENGTH } from '../src/keys/monero-words';
import { readFileSync } from 'node:fs';

const seedFrom = (text: string) => {
  // A deterministic 32 bytes, so every test here is reproducible.
  const out = new Uint8Array(32);
  for (let i = 0; i < 32; i++) out[i] = (text.charCodeAt(i % text.length) * (i + 7)) & 0xff;
  return reduceScalar(out);
};

describe('the word list', () => {
  it('is exactly 1626 words', () => {
    // Not a round number and not negotiable: the phrase encodes in base 1626.
    // A list one word short or long changes what every phrase decodes to.
    expect(MONERO_WORDS).toHaveLength(1626);
  });

  it('is unique in the first three characters', () => {
    // The checksum word is computed from three-character prefixes, so a
    // collision would make two different phrases indistinguishable to it.
    expect(new Set(MONERO_WORDS.map((w) => w.slice(0, PREFIX_LENGTH))).size).toBe(1626);
  });

  it('starts and ends where the Monero source does', () => {
    expect(MONERO_WORDS[0]).toBe('abbey');
    expect(MONERO_WORDS[1625]).toBe('zoom');
  });
});

describe('scalar reduction', () => {
  it('leaves a value already below the order alone', () => {
    const small = new Uint8Array(32);
    small[0] = 42;
    expect(toHex(reduceScalar(small))).toBe(toHex(small));
  });

  it('brings an out-of-range value into the field', () => {
    // All-ones is far above the group order; reducing must change it, and the
    // result must be below the order.
    const big = new Uint8Array(32).fill(0xff);
    const reduced = reduceScalar(big);
    expect(toHex(reduced)).not.toBe(toHex(big));
    // Top byte of the order is 0x10, so a reduced scalar cannot exceed it.
    expect(reduced[31]!).toBeLessThanOrEqual(0x10);
  });

  it('is idempotent, because a reduced scalar is already reduced', () => {
    const once = reduceScalar(new Uint8Array(32).fill(0xab));
    expect(toHex(reduceScalar(once))).toBe(toHex(once));
  });

  it('refuses anything that is not 32 bytes', () => {
    expect(() => reduceScalar(new Uint8Array(31))).toThrow();
  });
});

describe('public keys', () => {
  it('gives the published ed25519 base point for a scalar of one', () => {
    // The one external vector available for this step, and everybody agrees
    // on it.
    expect(toHex(publicFromSecret(fromHex('01' + '00'.repeat(31))))).toBe(
      '5866666666666666666666666666666666666666666666666666666666666666',
    );
  });

  it('refuses a zero scalar rather than returning the identity', () => {
    expect(() => publicFromSecret(new Uint8Array(32))).toThrow(/zero/i);
  });

  it('is deterministic', () => {
    const secret = seedFrom('determinism');
    expect(toHex(publicFromSecret(secret))).toBe(toHex(publicFromSecret(secret)));
  });

  it('gives different keys for different secrets', () => {
    expect(toHex(publicFromSecret(seedFrom('one')))).not.toBe(toHex(publicFromSecret(seedFrom('two'))));
  });
});

describe('key derivation', () => {
  it('derives the view key from the spend key, which is what one phrase restores', () => {
    const keys = keysFromSeed(seedFrom('derivation'));
    // Same seed, same view key, every time and in every implementation.
    expect(toHex(keysFromSeed(seedFrom('derivation')).viewSecret)).toBe(toHex(keys.viewSecret));
    expect(toHex(keys.viewSecret)).not.toBe(toHex(keys.spendSecret));
  });

  it('produces four distinct 32-byte values', () => {
    const keys = keysFromSeed(seedFrom('distinct'));
    const all = [keys.spendSecret, keys.viewSecret, keys.spendPublic, keys.viewPublic];
    for (const value of all) expect(value).toHaveLength(32);
    expect(new Set(all.map(toHex)).size).toBe(4);
  });

  it('gives a view secret that is a valid scalar', () => {
    const keys = keysFromSeed(seedFrom('reduced view'));
    expect(toHex(reduceScalar(keys.viewSecret))).toBe(toHex(keys.viewSecret));
  });
});

describe('base58, the Monero variant', () => {
  it('round-trips the real address to the character', () => {
    // The strongest check here: this address came out of the official Monero
    // wallet, not out of this code.
    expect(base58Encode(base58Decode(KNOWN_ADDRESS))).toBe(KNOWN_ADDRESS);
  });

  it('turns 69 bytes into 95 characters, which is what an address is', () => {
    expect(base58Decode(KNOWN_ADDRESS)).toHaveLength(69);
    expect(KNOWN_ADDRESS).toHaveLength(95);
  });

  it('round-trips arbitrary lengths, including the awkward partial block', () => {
    for (let length = 1; length <= 20; length++) {
      const bytes = new Uint8Array(length);
      for (let i = 0; i < length; i++) bytes[i] = (i * 37 + 11) & 0xff;
      expect(toHex(base58Decode(base58Encode(bytes))), `length ${length}`).toBe(toHex(bytes));
    }
  });

  it('keeps leading zero bytes, which a naive base58 loses', () => {
    const bytes = new Uint8Array([0, 0, 0, 1, 2, 3, 4, 5]);
    expect(toHex(base58Decode(base58Encode(bytes)))).toBe(toHex(bytes));
  });

  it('rejects a character outside the alphabet', () => {
    expect(() => base58Decode('0OIl' + 'a'.repeat(7))).toThrow(/base58/i);
  });
});

describe('parsing an address', () => {
  it('reads the known-good address correctly', () => {
    const parsed = parseAddress(KNOWN_ADDRESS);
    expect(parsed.valid).toBe(true);
    expect(parsed.network).toBe('mainnet');
    expect(parsed.kind).toBe('standard');
    expect(parsed.spendPublic).toHaveLength(64);
    expect(parsed.viewPublic).toHaveLength(64);
  });

  it('catches a single mistyped character', () => {
    // The entire point of a checksum, and the failure people actually hit.
    const broken = KNOWN_ADDRESS.slice(0, 40) + (KNOWN_ADDRESS[40] === 'a' ? 'b' : 'a') + KNOWN_ADDRESS.slice(41);
    const parsed = parseAddress(broken);
    expect(parsed.valid).toBe(false);
    expect(parsed.problem).toMatch(/checksum|mistyped|block/i);
  });

  it('catches truncation', () => {
    expect(parseAddress(KNOWN_ADDRESS.slice(0, 90)).valid).toBe(false);
  });

  it('says what is wrong rather than just failing', () => {
    expect(parseAddress('').problem).toBeTruthy();
    expect(parseAddress('not an address').problem).toBeTruthy();
    expect(parseAddress('4' + 'a'.repeat(94)).problem).toBeTruthy();
  });

  it('does not mistake a Bitcoin address for a Monero one', () => {
    expect(parseAddress('1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa').valid).toBe(false);
  });

  it('recognizes an address this code built', () => {
    const wallet = walletFromSeed(seedFrom('built here'));
    const parsed = parseAddress(wallet.address);
    expect(parsed.valid).toBe(true);
    expect(parsed.kind).toBe('standard');
    expect(parsed.spendPublic).toBe(wallet.spendPublic);
    expect(parsed.viewPublic).toBe(wallet.viewPublic);
  });

  it('tells the networks apart', () => {
    const keys = keysFromSeed(seedFrom('networks'));
    for (const network of ['mainnet', 'stagenet', 'testnet'] as const) {
      const address = addressFor(keys.spendPublic, keys.viewPublic, network);
      expect(parseAddress(address).network, network).toBe(network);
    }
  });

  it('gives mainnet addresses the 4 they are known by', () => {
    const keys = keysFromSeed(seedFrom('prefix four'));
    expect(addressFor(keys.spendPublic, keys.viewPublic, 'mainnet').startsWith('4')).toBe(true);
  });
});

describe('the seed phrase', () => {
  it('is 25 words', () => {
    expect(mnemonicFromSeed(seedFrom('twenty five'))).toHaveLength(25);
  });

  it('round-trips to the same bytes', () => {
    for (const label of ['a', 'longer input here', 'another one entirely', 'x']) {
      const seed = seedFrom(label);
      const back = seedFromMnemonic(mnemonicFromSeed(seed));
      expect(back.problem, label).toBeNull();
      expect(toHex(back.seed!), label).toBe(toHex(seed));
    }
  });

  it('repeats one of its own words as the checksum', () => {
    const phrase = mnemonicFromSeed(seedFrom('checksum word'));
    expect(phrase.slice(0, 24)).toContain(phrase[24]);
    expect(phrase[24]).toBe(phrase[checksumIndex(phrase.slice(0, 24))]);
  });

  it('catches a single word swapped for another real word', () => {
    // The case the checksum exists for: a word that is in the list, in the
    // wrong place, which nothing else would notice.
    const phrase = mnemonicFromSeed(seedFrom('swap detection'));
    const broken = [...phrase];
    broken[5] = MONERO_WORDS[(MONERO_WORDS.indexOf(broken[5]!) + 1) % 1626]!;
    const result = seedFromMnemonic(broken);
    expect(result.seed).toBeNull();
    expect(result.problem).toMatch(/last word should be/i);
  });

  it('names a word that is not in the list', () => {
    const phrase = mnemonicFromSeed(seedFrom('unknown word'));
    const broken = [...phrase];
    broken[3] = 'zzzznotaword';
    expect(seedFromMnemonic(broken).problem).toMatch(/zzzznotaword/);
  });

  it('counts the words and says the number', () => {
    expect(seedFromMnemonic('one two three').problem).toMatch(/25 words and this is 3/);
  });

  it('accepts a phrase as a string with any spacing, and ignores case', () => {
    const phrase = mnemonicFromSeed(seedFrom('spacing'));
    const messy = '  ' + phrase.join('   ').toUpperCase() + '\n';
    expect(toHex(seedFromMnemonic(messy).seed!)).toBe(toHex(seedFromMnemonic(phrase).seed!));
  });

  it('restores to the same wallet it came from', () => {
    // The property that matters most to somebody holding a piece of paper.
    const wallet = walletFromSeed(seedFrom('restore me'));
    const restored = walletFromMnemonic(revealMnemonic(wallet));
    expect('problem' in restored).toBe(false);
    expect((restored as typeof wallet).address).toBe(wallet.address);
    expect((restored as typeof wallet).spendSecret).toEqual(wallet.spendSecret);
  });
});

describe('crc32 and the checksum word', () => {
  it('matches the published value for a known string', () => {
    // The standard IEEE CRC-32 check value.
    expect(crc32('123456789') >>> 0).toBe(0xcbf43926);
  });

  it('picks the same checksum word Monero itself picks', () => {
    // The one place a step of this derivation can be checked against the
    // official implementation's own output rather than against a round trip.
    // This seed and its checksum word are lifted from Monero's unit tests
    // (tests/unit_tests/mnemonics.cpp, the bad-checksum language-detection
    // case). Portuguese, so four-character prefixes rather than three, which
    // is why checksumIndex takes the length as an argument.
    const portuguese = ('cinzento luxuriante leonardo gnostico digressao cupula fifa broxar iniquo ' +
      'louvor ovario dorsal ideologo besuntar decurso rosto susto lemure unheiro pagodeiro ' +
      'nitroglicerina eclusa mazurca bigorna').split(' ');
    expect(portuguese).toHaveLength(24);
    expect(portuguese[checksumIndex(portuguese, 4)]).toBe('gnostico');
  });

  it('would not match if the prefix length were wrong', () => {
    // Guards the test above from passing by luck: three characters must give
    // a different answer, or it is proving nothing about the prefix rule.
    const portuguese = ('cinzento luxuriante leonardo gnostico digressao cupula fifa broxar iniquo ' +
      'louvor ovario dorsal ideologo besuntar decurso rosto susto lemure unheiro pagodeiro ' +
      'nitroglicerina eclusa mazurca bigorna').split(' ');
    expect(checksumIndex(portuguese, 3)).not.toBe(checksumIndex(portuguese, 4));
  });
});

describe('a wallet', () => {
  it('writes its phrase from the reduced key, not the raw seed', () => {
    // The subtle, silent, expensive bug this whole file is careful about: if
    // the phrase encoded unreduced randomness, the words on the paper would
    // restore to a different wallet than the address printed beside them.
    const raw = new Uint8Array(32).fill(0xff);
    const wallet = walletFromSeed(raw);
    const restored = walletFromMnemonic(revealMnemonic(wallet)) as typeof wallet;
    expect(restored.address).toBe(wallet.address);
    expect(restored.spendSecret).toEqual(wallet.spendSecret);
    // And the seed really was out of range, so this test is testing something.
    expect(toHex(reduceScalar(raw))).not.toBe(toHex(raw));
  });

  it('is entirely determined by its seed', () => {
    const a = walletFromSeed(seedFrom('same'));
    const b = walletFromSeed(seedFrom('same'));
    expect(a).toEqual(b);
  });

  it('keeps secrets as bytes and public facts as hex', () => {
    /* The split is a security property, not a style: a string cannot be
     * overwritten, so anything secret has to be a buffer to be wipeable. */
    const wallet = walletFromSeed(seedFrom('fields'));
    for (const key of ['spendSecret', 'viewSecret'] as const) {
      expect(wallet[key], key).toBeInstanceOf(Uint8Array);
      expect(wallet[key], key).toHaveLength(32);
    }
    for (const key of ['spendPublic', 'viewPublic'] as const) {
      expect(wallet[key], key).toMatch(/^[0-9a-f]{64}$/);
    }
  });

  it('reports a bad phrase rather than throwing', () => {
    expect(walletFromMnemonic('not a real phrase')).toHaveProperty('problem');
  });
});

describe('the self test the page runs before it will generate anything', () => {
  it('passes, in full', () => {
    const checks = selfTest();
    const failed = checks.filter((c) => !c.ok);
    expect(failed.map((c) => `${c.name}: ${c.detail}`)).toEqual([]);
    expect(allChecksPass(checks)).toBe(true);
  });

  it('checks the things that would be silent failures', () => {
    const names = selfTest().map((c) => c.name.toLowerCase());
    expect(names.some((n) => n.includes('keccak'))).toBe(true);
    expect(names.some((n) => n.includes('base point'))).toBe(true);
    expect(names.some((n) => n.includes('real address'))).toBe(true);
    expect(names.some((n) => n.includes('phrase'))).toBe(true);
  });

  it('says what each check proves, not just whether it passed', () => {
    // A green tick nobody can interpret is decoration. The page prints these.
    for (const check of selfTest()) {
      expect(check.proves.length, check.name).toBeGreaterThan(30);
    }
  });

  it('reports failure rather than throwing when something is broken', () => {
    expect(allChecksPass([{ name: 'x', proves: 'y', ok: false, detail: '' }])).toBe(false);
    expect(allChecksPass([])).toBe(false);
  });
});

describe('the known-good address, which is the only outside witness here', () => {
  /* Everything else in this file checks our code against our code. This one
   * string was produced by the official Monero wallet, so decoding it is the
   * one assertion that can catch a base58 or Keccak change that is
   * self-consistently wrong. Do not replace it with an address generated by
   * the code above: that would make the test pass by definition. */

  it('is a valid mainnet address', () => {
    const parsed = parseAddress(KNOWN_ADDRESS);
    expect(parsed.valid).toBe(true);
    expect(parsed.network).toBe('mainnet');
  });

  it('survives a decode and re-encode unchanged, to the character', () => {
    expect(base58Encode(base58Decode(KNOWN_ADDRESS))).toBe(KNOWN_ADDRESS);
  });

  it('carries the checksum the official wallet put on it', () => {
    // Recomputing it here means our Keccak agrees with the one that made it.
    const raw = base58Decode(KNOWN_ADDRESS);
    const body = raw.subarray(0, raw.length - 4);
    expect(toHex(addressChecksum(body))).toBe(toHex(raw.subarray(raw.length - 4)));
  });
});

describe('mixing in your own entropy', () => {
  const browser = () => {
    const b = new Uint8Array(32);
    for (let i = 0; i < 32; i++) b[i] = (i * 91 + 5) & 0xff;
    return b;
  };

  it('hashes, rather than returning the input', () => {
    // The bug this replaced: a version that folded bytes together without
    // hashing, while the page said it hashed. Same length, plausible output,
    // completely different property.
    expect(toHex(mixEntropy(browser()))).not.toBe(toHex(browser()));
  });

  it('changes completely when one character of the extra changes', () => {
    const a = mixEntropy(browser(), new TextEncoder().encode('6 4 2 1 5 3'));
    const b = mixEntropy(browser(), new TextEncoder().encode('6 4 2 1 5 4'));
    expect(toHex(a)).not.toBe(toHex(b));
    // And not merely in the last byte: a hash, not a checksum.
    const differing = [...a].filter((byte, i) => byte !== b[i]).length;
    expect(differing).toBeGreaterThan(20);
  });

  it('is deterministic for the same inputs', () => {
    const extra = new TextEncoder().encode('dice');
    expect(toHex(mixEntropy(browser(), extra))).toBe(toHex(mixEntropy(browser(), extra)));
  });

  it('works with no extra at all', () => {
    expect(mixEntropy(browser())).toHaveLength(32);
    expect(mixEntropy(browser(), new Uint8Array(0))).toHaveLength(32);
  });

  it('insists the browser actually supplied 32 bytes', () => {
    expect(() => mixEntropy(new Uint8Array(16))).toThrow(/32 bytes/);
  });

  it('produces a usable wallet', () => {
    const wallet = walletFromSeed(mixEntropy(browser(), new TextEncoder().encode('4 4 6 1')));
    expect(parseAddress(wallet.address).valid).toBe(true);
  });
});

describe('the block height estimate', () => {
  it('puts the v2 fork where it actually happened', () => {
    // Two block-time eras, not one. A single 120-second model is out by most
    // of a million blocks, which would send a wallet scanning from years too
    // late. This landmark is what pins the first era.
    const forkDate = new Date(Date.UTC(2016, 2, 19));
    expect(Math.abs(approximateHeight(forkDate) - 1_009_827)).toBeLessThan(2000);
  });

  it('puts height three million in late 2023', () => {
    // An independent landmark from the other era.
    const height = approximateHeight(Date.UTC(2023, 9, 13));
    expect(Math.abs(height - 3_000_000)).toBeLessThan(5000);
  });

  it('is zero before Monero existed', () => {
    expect(approximateHeight(Date.UTC(2010, 0, 1))).toBe(0);
    expect(approximateHeight(Date.UTC(2014, 3, 18))).toBe(0);
  });

  it('only ever goes up', () => {
    let previous = -1;
    for (const year of [2015, 2017, 2019, 2021, 2023, 2025]) {
      const height = approximateHeight(Date.UTC(year, 0, 1));
      expect(height).toBeGreaterThan(previous);
      previous = height;
    }
  });
});

describe('the restore height', () => {
  it('errs early, never late', () => {
    // The direction is the whole point. Too early costs patience; too late
    // means the wallet silently never sees payments that already arrived and
    // the balance reads zero with no explanation.
    const now = Date.UTC(2026, 6, 1);
    expect(restoreHeight(now)).toBeLessThan(approximateHeight(now));
  });

  it('backs off by about a week', () => {
    const now = Date.UTC(2026, 6, 1);
    const blocksBack = approximateHeight(now) - restoreHeight(now);
    // A week at two-minute blocks.
    expect(blocksBack).toBe(7 * 24 * 30);
  });

  it('never goes below zero', () => {
    expect(restoreHeight(Date.UTC(2014, 3, 19))).toBe(0);
  });
});

describe('the watch-only export', () => {
  const wallet = () => walletFromSeed(seedFrom('watch me'));

  it('carries the address and the view key, and never the spend key', () => {
    // The single most important property here. A "watch-only" export that
    // included the spend key would be a full wallet wearing a safe name.
    const w = wallet();
    const view = revealSecretHex(w.viewSecret);
    const spend = revealSecretHex(w.spendSecret);
    const exported = watchOnlyExport(w.address, view, Date.UTC(2026, 6, 1));
    expect(exported.json).toContain(view);
    expect(exported.json).toContain(w.address);
    expect(exported.json).not.toContain(spend);
    expect(JSON.stringify(exported)).not.toContain(spend);
  });

  it('produces JSON the restore format expects', () => {
    const w = wallet();
    const view = revealSecretHex(w.viewSecret);
    const parsed = JSON.parse(watchOnlyExport(w.address, view, Date.UTC(2026, 6, 1)).json);
    expect(parsed).toMatchObject({ version: 1, viewkey: view, address: w.address });
    expect(parsed.scan_from_height).toBeGreaterThan(3_000_000);
    expect('spendkey' in parsed).toBe(false);
  });

  it('names the command to run', () => {
    const w = wallet();
    const exported = watchOnlyExport(w.address, revealSecretHex(w.viewSecret));
    expect(exported.steps[0]).toContain('--generate-from-view-key');
    expect(exported.steps.join(' ')).toMatch(/view key/i);
  });

  it('sets a restore height rather than starting from genesis', () => {
    const exported = watchOnlyExport('4addr', 'viewkey', Date.UTC(2026, 6, 1));
    expect(exported.height).toBe(restoreHeight(Date.UTC(2026, 6, 1)));
  });
});

describe('what can be watched', () => {
  it('accepts a standard address', () => {
    expect(canWatch(parseAddress(walletFromSeed(seedFrom('standard')).address)).ok).toBe(true);
  });

  it('refuses a subaddress, and explains why', () => {
    /* --generate-from-view-key wants the wallet's primary address. Given a
     * subaddress it builds a wallet that quietly watches the wrong thing,
     * which is only discovered after a long sync shows nothing.
     *
     * The subaddress is assembled here rather than pasted, because prefix 42
     * with the same key material is exactly what makes one: it is the prefix
     * byte being tested, not the encoding, which KNOWN_ADDRESS already covers
     * against the official wallet. */
    const wallet = walletFromSeed(seedFrom('subaddress'));
    const body = new Uint8Array(65);
    body[0] = 42; // mainnet subaddress
    body.set(fromHex(wallet.spendPublic), 1);
    body.set(fromHex(wallet.viewPublic), 33);
    const full = new Uint8Array(69);
    full.set(body);
    full.set(addressChecksum(body), 65);
    const subaddress = base58Encode(full);

    expect(parseAddress(subaddress).kind, 'the fixture really is a subaddress').toBe('subaddress');
    const result = canWatch(parseAddress(subaddress));
    expect(result.ok).toBe(false);
    expect(result.problem).toMatch(/primary address/i);
  });

  it('passes on the reason an address was invalid', () => {
    expect(canWatch(parseAddress('nonsense')).problem).toBeTruthy();
  });
});

describe('secrets are bytes, and bytes can be wiped', () => {
  /* The audit finding this API exists to answer: a JavaScript string is
   * immutable, so a secret that has ever been one cannot be overwritten and
   * lives until the collector moves it. Anything secret is therefore a buffer,
   * and turning one into text is a function with "reveal" in the name so the
   * moment it becomes permanent is visible at the call site. */

  it('hands back no secret as a string, anywhere in the object', () => {
    const wallet = walletFromSeed(seedFrom('no strings'));
    const spendHex = toHex(wallet.spendSecret);
    const viewHex = toHex(wallet.viewSecret);
    for (const [key, value] of Object.entries(wallet)) {
      if (typeof value !== 'string') continue;
      expect(value, `${key} contains the spend key`).not.toContain(spendHex);
      expect(value, `${key} contains the view key`).not.toContain(viewHex);
    }
    // And the whole object serialized, which is what a careless log would do.
    const serialized = JSON.stringify(wallet);
    expect(serialized).not.toContain(spendHex);
    expect(serialized).not.toContain(viewHex);
  });

  it('does not compute the recovery phrase until it is asked to', () => {
    // A wallet that only ever signs never materialises an unwipeable copy of
    // its own words.
    const wallet = walletFromSeed(seedFrom('lazy phrase'));
    expect('mnemonic' in wallet).toBe(false);
    expect(revealMnemonic(wallet)).toHaveLength(25);
  });

  it('wipes both secrets in place, leaving the public half usable', () => {
    const wallet = walletFromSeed(seedFrom('wipe me'));
    const address = wallet.address;
    wipeWallet(wallet);
    expect(toHex(wallet.spendSecret)).toBe('00'.repeat(32));
    expect(toHex(wallet.viewSecret)).toBe('00'.repeat(32));
    expect(wallet.address, 'the public half survives').toBe(address);
  });

  it('reveals everything through one door, and it matches the bytes', () => {
    const wallet = walletFromSeed(seedFrom('reveal'));
    const shown = revealWallet(wallet);
    expect(shown.spendSecret).toBe(revealSecretHex(wallet.spendSecret));
    expect(shown.viewSecret).toBe(revealSecretHex(wallet.viewSecret));
    expect(shown.mnemonic).toEqual(revealMnemonic(wallet));
    expect(shown.address).toBe(wallet.address);
  });

  it('still round-trips through the phrase after the change', () => {
    // The property that matters to somebody holding a piece of paper, checked
    // again now that the phrase comes from a different place.
    const wallet = walletFromSeed(seedFrom('paper'));
    const restored = walletFromMnemonic(revealMnemonic(wallet)) as typeof wallet;
    expect(restored.address).toBe(wallet.address);
    expect(toHex(restored.spendSecret)).toBe(toHex(wallet.spendSecret));
    expect(toHex(restored.viewSecret)).toBe(toHex(wallet.viewSecret));
  });
});

describe('formatting piconero', () => {
  it('formats whole, fractional and mixed amounts, zeros trimmed', async () => {
    const { formatXmr } = await import('../src/keys/monero');
    expect(formatXmr(0n)).toBe('0');
    expect(formatXmr(1_000_000_000_000n)).toBe('1');
    expect(formatXmr(600_000_000_000n)).toBe('0.6');
    expect(formatXmr(720_000_000n)).toBe('0.00072');
    expect(formatXmr(14_732_810_450_000n)).toBe('14.73281045');
    expect(formatXmr(1n)).toBe('0.000000000001');
    expect(formatXmr(-600_000_000_000n)).toBe('-0.6');
  });
});

describe("addresses and seed phrases, against Monero's own encoders", () => {
  /* Everything else in this file about addresses and phrases is a round trip:
   * encode then decode, split then rejoin, the checksum word sits where the
   * checksum function says. That proves an encoder and a decoder agree, and it
   * is exactly the shape of test that let two mistakes live in CLSAG for
   * months. One real anchor existed - KNOWN_ADDRESS, the Monero project's
   * donation address - and it anchors parsing one mainnet standard address.
   *
   * These two artifacts are the ones a person holds, and the failures are the
   * worst kind: silent and late.
   *
   *   A wrong address is money sent where nobody can spend it, and the
   *   watch-only companion derives from this same code, so both screens would
   *   agree and nothing would look wrong until a third wallet disagreed.
   *
   *   A wrong seed phrase is a backup that restores in no other wallet. The
   *   person finds out on the day the phone is gone, which is the one day it
   *   cannot be fixed.
   *
   * `oracle/src/address.cpp` asks Monero: get_account_address_as_str,
   * get_account_integrated_address_as_str, hw::device::get_subaddress, and
   * ElectrumWords::bytes_to_words. Three secrets across three networks, and
   * the leading-zeros one is there because a base58 written from Bitcoin's
   * eats a zero byte that Monero's block encoding keeps.
   */
  const fixture = JSON.parse(readFileSync('test/fixtures/monero-address.json', 'utf8')) as {
    accounts: {
      name: string;
      network: Network;
      spendSecret: string;
      viewSecret: string;
      spendPublic: string;
      viewPublic: string;
      address: string;
      paymentId: string;
      integrated: string;
      mnemonic: string[];
      subaddresses: { major: number; minor: number; spendPublic: string; viewPublic: string; address: string }[];
    }[];
  };

  it('covers three networks and the awkward secrets', () => {
    expect(fixture.accounts.length).toBe(9);
    expect(new Set(fixture.accounts.map((a) => a.network))).toEqual(
      new Set(['mainnet', 'stagenet', 'testnet']),
    );
    expect(fixture.accounts.some((a) => a.name === 'leading-zeros')).toBe(true);
  });

  for (const account of fixture.accounts) {
    describe(`${account.name} on ${account.network}`, () => {
      const wallet = walletFromSeed(fromHex(account.spendSecret), account.network);

      it('derives the same view secret and the same public keys', () => {
        /* The deterministic-wallet rule, which is Monero's and not ours: the
         * view secret is the reduced Keccak of the spend secret. Asked for
         * rather than asserted. */
        expect(toHex(wallet.viewSecret)).toBe(account.viewSecret);
        expect(wallet.spendPublic).toBe(account.spendPublic);
        expect(wallet.viewPublic).toBe(account.viewPublic);
      });

      it('encodes the address Monero encodes', () => {
        expect(wallet.address).toBe(account.address);
        expect(addressFor(fromHex(account.spendPublic), fromHex(account.viewPublic), account.network))
          .toBe(account.address);
      });

      it('reads back what Monero wrote', () => {
        const parsed = parseAddress(account.address);
        expect(parsed.valid).toBe(true);
        expect(parsed.network).toBe(account.network);
        expect(parsed.kind).toBe('standard');
        expect(parsed.spendPublic).toBe(account.spendPublic);
        expect(parsed.viewPublic).toBe(account.viewPublic);
      });

      it('reads back the integrated address, payment id and all', () => {
        /* This vault does not write integrated addresses, but it will be shown
         * one and has to say what it is. A wrong prefix table or a wrong
         * length would make it call a real address invalid. */
        const parsed = parseAddress(account.integrated);
        expect(parsed.valid, account.integrated).toBe(true);
        expect(parsed.kind).toBe('integrated');
        expect(parsed.network).toBe(account.network);
        expect(parsed.spendPublic).toBe(account.spendPublic);
        expect(parsed.viewPublic).toBe(account.viewPublic);
        expect(parsed.paymentId).toBe(account.paymentId);
      });

      it('produces the same twenty-five words', () => {
        /* The one that would fail on the worst possible day. Monero's
         * wordlist, Monero's checksum, Monero's ordering. */
        expect(mnemonicFromSeed(wallet.spendSecret)).toEqual(account.mnemonic);
      });

      it('restores the same wallet from those words', () => {
        const back = walletFromMnemonic(account.mnemonic, account.network);
        expect('problem' in back ? back.problem : '').toBe('');
        expect((back as typeof wallet).address).toBe(account.address);
      });

      it('derives every subaddress Monero derives', () => {
        for (const sub of account.subaddresses) {
          const keys = subaddressKeys(
            fromHex(account.spendPublic), wallet.viewSecret, sub.major, sub.minor,
          );
          const where = `(${sub.major}, ${sub.minor})`;
          expect(toHex(keys.spend), `${where} spend`).toBe(sub.spendPublic);
          /* (0, 0) is the main address and is encoded with the standard tag,
           * not the subaddress tag. Its view key is a·G, not a·D - which is
           * the distinction this fixture caught us getting wrong. */
          expect(toHex(keys.view), `${where} view`).toBe(sub.viewPublic);
          const main = sub.major === 0 && sub.minor === 0;
          const encoded = main
            ? addressFor(keys.spend, keys.view, account.network)
            : subaddressFor(keys.spend, keys.view, account.network);
          expect(encoded, `${where} address`).toBe(sub.address);
        }
      });
    });
  }
});
