/*
 * The oracle is committed, and it is the same Monero as the vendored copy.
 *
 * ## What this guards
 *
 * A good part of this repository's Monero work is checked against numbers that
 * came out of Monero's own C++: the CryptoNight vectors, every ring signature
 * in the key-image export, the whole finished blob. Those numbers are only
 * worth anything if somebody can regenerate them, and until now the thing that
 * produced them lived in a git-ignored scratch directory. It was lost once,
 * between sessions, and had to be rebuilt from a fresh clone.
 *
 * That is the failure this file exists to stop repeating. `oracle/` is now
 * committed: a build recipe, five small harness sources, and a regenerator.
 * `./oracle/build.sh --check && node oracle/emit.mjs --check` rebuilds every
 * fixture from Monero at the pinned tag and diffs it against what is in the
 * tree, so "these came from Monero" is a claim a reviewer can run rather than
 * one they have to accept.
 *
 * ## What it deliberately does not do
 *
 * It does not run the oracle. That needs a Monero checkout and a C++ toolchain
 * with boost headers, and a suite which fetched half a gigabyte of upstream
 * C++ would be a suite people learn to skip — at which point the checking
 * stops happening at all. What runs here is cheap and catches the things that
 * actually drift: the pins disagreeing with each other, a harness going
 * missing, a fixture losing its provenance.
 */
import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';

const pinned: {
  upstream: string;
  tag: string;
  commit: string;
  produces: string[];
  bitcoin: {
    electrum: { repo: string; commit: string };
    bbqr: { repo: string; spec: string };
    produces: string[];
  };
} = JSON.parse(readFileSync('oracle/PINNED.json', 'utf8'));

const vendored: { upstream: string; tag: string; commit: string } = JSON.parse(
  readFileSync('vendor/cryptonight/MANIFEST.json', 'utf8'),
);

describe('the oracle rig', () => {
  it('pins the same Monero the app actually ships', () => {
    /* The load-bearing one. vendor/cryptonight is compiled into the app; the
     * oracle is what its fixtures were measured against. If those two drift
     * apart, every cross-language check in the repository is comparing one
     * version of Monero to another and calling the agreement a proof.
     *
     * `CryptoNightVectorTests.swift` asserts the vendored C reproduces the
     * fixture's chacha key, and that assertion is only meaningful while this
     * one holds. */
    expect(pinned.upstream).toBe(vendored.upstream);
    expect(pinned.tag).toBe(vendored.tag);
    expect(pinned.commit).toBe(vendored.commit);
    expect(pinned.commit).toMatch(/^[0-9a-f]{40}$/);
  });

  it('still has every piece the recipe needs', () => {
    /* Cheap, and it catches the thing that actually happened once: the rig
     * disappearing. A missing harness is not noticed by any other test,
     * because nothing in `npm test` compiles it. */
    for (const path of [
      'oracle/build.sh',
      'oracle/emit.mjs',
      'oracle/PINNED.json',
      'oracle/README.md',
      'oracle/src/cryptonight.c',
      'oracle/src/keyimage.cpp',
      'oracle/src/rng-counter.c',
      'oracle/src/mlock-stub.cpp',
      'oracle/src/unreachable.c',
      'oracle/src/importkeyimages.cpp',
      'oracle/src/wallet-unreachable.cpp',
      'oracle/src/shim/boost/preprocessor/stringize.hpp',
      'oracle/btc.sh',
      'oracle/btc-emit.mjs',
    ]) {
      expect(existsSync(path), `${path} is gone`).toBe(true);
    }
  });

  it('produces every fixture it claims to', () => {
    for (const path of pinned.produces) {
      expect(existsSync(path), `${path} is claimed but missing`).toBe(true);
      const fixture = JSON.parse(readFileSync(path, 'utf8'));
      /* The fixture has to name the same tag, or it predates the pin and
       * nobody would know. */
      expect(fixture.source?.tag, `${path} does not name its Monero tag`).toBe(pinned.tag);
      expect(fixture.note, `${path} does not say where it came from`).toMatch(/oracle\//);
    }
    expect(pinned.produces.length).toBeGreaterThan(0);
  });

  it('pins the Bitcoin wallets its fixtures were measured against', () => {
    /* The Bitcoin side is Python rather than C++, and for a while it had no
     * rig at all: the commits were recorded in a doc and the fixtures were
     * generated by hand. Same weakness as the Monero side had, same fix. */
    expect(pinned.bitcoin.electrum.commit).toMatch(/^[0-9a-f]{40}$/);
    expect(pinned.bitcoin.bbqr.repo).toContain('BBQr');
    for (const path of pinned.bitcoin.produces) {
      expect(existsSync(path), `${path} is claimed but missing`).toBe(true);
      const fixture = JSON.parse(readFileSync(path, 'utf8'));
      expect(fixture.note, `${path} does not say how to regenerate it`).toMatch(/oracle\/btc-emit/);
    }
  });

  it('records that the BBQr reference accepted our frames, not just that it exists', () => {
    /* The distinction the wallet-wires fixture turns on. Its `electrumBase43`
     * is Electrum's output and can simply be copied; its `bbqrFrames` are
     * *ours*, and the only thing that makes them worth anything is that
     * Coinkite's own joiner reassembled them into the original PSBT. So the
     * regenerator has to hand them over and check, and it exits non-zero if
     * they are refused. A version that copied the reference's own frames
     * instead would be testing nothing. */
    const emit = readFileSync('oracle/btc-emit.mjs', 'utf8');
    expect(emit).toContain('join_qrs');
    expect(emit).toMatch(/bbqrAccepted/);
    expect(emit).toMatch(/did NOT accept our frames/);
  });

  it('keeps the RNG stub, which is the only reason signatures are comparable', () => {
    /* Monero draws a nonce inside `generate_signature` and
     * `generate_ring_signature`. Two correct implementations of those produce
     * different bytes on the same input, so without a deterministic RNG there
     * is no fixture to write and nothing to compare the TypeScript against.
     *
     * If somebody ever "fixes" this stub to use real randomness, the fixtures
     * stop reproducing and the reason will not be obvious. */
    const stub = readFileSync('oracle/src/rng-counter.c', 'utf8');
    expect(stub).toContain('generate_random_bytes_thread_safe');
    expect(stub).toMatch(/counter\+\+|counter \+ i/);
  });

  it('builds the same CryptoNight the phone runs', () => {
    /* NO_AES picks the portable implementation out of the three inside
     * slow-hash.c. vendor/cryptonight ships that one, so the oracle has to
     * build it too — otherwise the fixtures are measured against a code path
     * the app never executes, and all three implementations agreeing on four
     * vectors is doing the work that a test was supposed to do. */
    const build = readFileSync('oracle/build.sh', 'utf8');
    expect(build).toContain('-DNO_AES');
    expect(build).toContain('-DFORCE_USE_HEAP');
    const defines = (JSON.parse(readFileSync('vendor/cryptonight/MANIFEST.json', 'utf8')) as {
      buildDefines: Record<string, string>;
    }).buildDefines;
    for (const define of Object.keys(defines)) {
      expect(build, `oracle/build.sh does not set ${define}, which the vendored build does`)
        .toContain(`-D${define}`);
    }
  });

  it('refuses to build against a Monero that is not the pinned one', () => {
    /* A tag can move, a mirror can lie, and a half-finished checkout looks
     * like a finished one. The recipe checks the commit it actually got. */
    const build = readFileSync('oracle/build.sh', 'utf8');
    expect(build).toContain('rev-parse HEAD');
    expect(build).toMatch(/refusing to build against a different Monero/);
  });
});

describe('the oracle reports Monero verifying its own output', () => {
  /* The gate an importing wallet applies, recorded by the implementation that
   * applies it. Without this the fixture proves only that two signers agree
   * about bytes; with it, the file is known to pass the check
   * `wallet2::import_key_images` runs before it accepts a record.
   *
   * Asserted here rather than only in the harness because `npm test` cannot
   * build C++. The committed answer is what the TypeScript suite reads, and
   * `./oracle/build.sh && node oracle/emit.mjs --check` is what proves the
   * answer is still what Monero gives.
   */
  const fixture = JSON.parse(
    readFileSync('test/fixtures/monero-keyimages.json', 'utf8'),
  ) as {
    cases: { name: string; ringSigs: string[]; verified?: { ringSignatures: boolean[]; envelope: boolean } };
  } & { cases: { name: string; ringSigs: string[]; verified: { ringSignatures: boolean[]; envelope: boolean } }[] };

  it('records a verdict for every record it wrote', () => {
    for (const one of fixture.cases) {
      expect(one.verified, `${one.name} has no recorded verdict`).toBeDefined();
      expect(one.verified.ringSignatures, one.name).toHaveLength(one.ringSigs.length);
    }
  });

  it('says Monero accepted all of them', () => {
    /* A false here would not be a failing test to work around. It would mean
     * the vault writes files real Monero software rejects, and everything
     * downstream of that is moot. */
    for (const one of fixture.cases) {
      expect(one.verified.ringSignatures.every(Boolean), `${one.name} ring signatures`).toBe(true);
      expect(one.verified.envelope, `${one.name} envelope`).toBe(true);
    }
  });

  it('is produced by the harness rather than written by hand', () => {
    const harness = readFileSync('oracle/src/keyimage.cpp', 'utf8');
    expect(harness).toMatch(/crypto::check_ring_signature\(\(const crypto::hash &\)ki, ki, ptrs, &sig\)/);
    expect(harness).toMatch(/crypto::check_signature\(h, view_pub, osig\)/);
    const emit = readFileSync('oracle/emit.mjs', 'utf8');
    expect(emit).toMatch(/ringSignatures: r\.ring_ok/);
    expect(emit).toMatch(/envelope: r\.outer_ok === '1'/);
  });
});

describe("Monero's own wallet, importing a file this repository wrote", () => {
  /* The last claim in the key-image story that was read rather than run.
   *
   * `import_key_images` pairs record n with `m_transfers[n + offset]`. Nothing
   * in the file names an output, so a file whose records are in the wrong
   * order is still well formed, still fully signed, and still wrong. Every
   * signature in it verifies; they just verify against outputs the importing
   * wallet is not holding at those positions.
   *
   * `oracle/src/importkeyimages.cpp` links wallet2.cpp and runs the real
   * `tools::wallet2::import_key_images` against files written here, in the
   * right order and in several wrong ones. This block reads the verdicts, and
   * rebuilds the exact bytes those verdicts were given, so a change to the
   * writer cannot quietly inherit an old answer.
   */
  const fixture = JSON.parse(
    readFileSync('test/fixtures/monero-import-key-images.json', 'utf8'),
  ) as {
    pad: number;
    wallet: { seed: string; chachaKey: string; viewSecret: string; spendPublic: string };
    outputs: { tx: string; index: number; key: string }[];
    keyImages: string[];
    cases: {
      name: string;
      order: number[];
      offset: number;
      account: string;
      randomness: string;
      file: string;
      outcome: string;
      detail: string;
      imported: number | null;
      transferKeyImages: string[];
    }[];
  };

  const named = (name: string) => {
    const one = fixture.cases.find((each) => each.name === name);
    expect(one, `the fixture has no ${name} case`).toBeDefined();
    return one!;
  };

  /** The identity point, which is what `generate_key_image` gives a watch-only
   *  wallet: it has no spend secret to multiply by, so the placeholder is
   *  `0·H(P)`. Every transfer wallet2 did not write to still holds one. */
  const PLACEHOLDER = '01' + '00'.repeat(31);

  it('accepted the file, and put each record where the offset said', () => {
    const accepted = named('accepted');
    /* Reaching the daemon is the accepting outcome. The magic, the envelope
     * signature, the account match, the offset bound, the record count and
     * every ring signature were all decided first, and decided in the file's
     * favour; then it went to ask a daemon which images were already spent,
     * and there is no daemon. */
    expect(accepted.outcome).toBe('no_connection_to_daemon');

    /* The part that is not about cryptography at all. Record i is now sitting
     * in transfer i + pad, and nothing below pad was touched. */
    expect(accepted.transferKeyImages).toHaveLength(fixture.pad + fixture.outputs.length);
    for (let i = 0; i < fixture.pad; i++) {
      expect(accepted.transferKeyImages[i], `transfer ${i} was written to`).toBe(PLACEHOLDER);
    }
    for (const [i, image] of fixture.keyImages.entries()) {
      expect(accepted.transferKeyImages[fixture.pad + i], `record ${i}`).toBe(image);
    }
  });

  it('rejected the same records in the wrong order', () => {
    /* The whole reason the offset is carried and the reason a file is refused
     * whole rather than exported short. Both of these files are valid: every
     * signature in them verifies against the key it was made for. */
    for (const name of ['records-reversed', 'offset-one-short']) {
      const one = named(name);
      expect(one.outcome, name).toBe('signature_check_failed');
      expect(one.detail, name).toMatch(/Signature check failed/);
      /* And nothing was written. wallet2 checks every record before it stores
       * any of them, so a rejected file leaves the wallet as it was. */
      for (const image of one.transferKeyImages) expect(image, name).toBe(PLACEHOLDER);
    }
  });

  it('rejected an offset past the end, and files for another account', () => {
    expect(named('offset-one-long').detail).toMatch(/blockchain is out of date/);
    /* A different account cannot even open the envelope: the outer signature
     * is over the ciphertext and made with the view key. */
    expect(named('another-account').detail).toMatch(/authenticate/);
    /* And one that can open it is still refused, because the plaintext names
     * the account's public keys. */
    expect(named('same-view-key-other-spend-key').detail).toMatch(/for a different account/);
  });

  it('gave those verdicts to bytes this code still produces', async () => {
    /* Without this, the fixture is a verdict about a file nobody can rebuild,
     * and a later change to the writer would inherit an answer that was given
     * to different bytes. Each case is rewritten from the recorded seed,
     * outputs, order, offset and randomness, and has to come out identical.
     *
     * The CryptoNight the writer needs is the one recorded in the fixture,
     * which oracle/emit.mjs took from the harness that build.sh holds to
     * Monero's four official vectors. One call, because the KDF runs one
     * round. */
    const { walletFromSeed, fromHex, toHex } = await import('../src/keys/monero');
    const { keyImageFileFor, KEYIMAGE_VERSION } = await import('../src/keys/keyimages');
    const { setNativeCnSlowHash } = await import('../src/keys/moneroexport');

    const chachaKey = fromHex(fixture.wallet.chachaKey);
    setNativeCnSlowHash(() => chachaKey);
    try {
      const wallet = walletFromSeed(fromHex(fixture.wallet.seed));
      expect(toHex(wallet.viewSecret)).toBe(fixture.wallet.viewSecret);
      expect(wallet.spendPublic).toBe(fixture.wallet.spendPublic);

      for (const each of fixture.cases) {
        const made = keyImageFileFor(
          wallet,
          {
            v: KEYIMAGE_VERSION,
            chain: 'xmr',
            outputs: each.order.map((i) => fixture.outputs[i]!),
            offset: each.offset,
          },
          fromHex(each.randomness),
        );
        expect(made.ok, `${each.name}: ${made.problem ?? ''}`).toBe(true);
        expect(toHex(made.file!), each.name).toBe(each.file);
      }
    } finally {
      setNativeCnSlowHash(null);
    }
  });

  it('is produced by a harness that calls import_key_images itself', () => {
    /* The guard against this whole block becoming a description of something
     * that no longer happens. `import_key_images` has to be the call, on a
     * wallet whose outputs went in through `import_outputs`, and the file has
     * to be one the vault wrote rather than one the harness made for itself. */
    const harness = readFileSync('oracle/src/importkeyimages.cpp', 'utf8');
    expect(harness).toMatch(/wallet\.import_key_images\(argv\[6\], spent, unspent\)/);
    expect(harness).toMatch(/wallet\.import_outputs\(/);
    expect(harness).toMatch(/wallet\.get_transfers\(after\)/);
    const emit = readFileSync('oracle/emit.mjs', 'utf8');
    expect(emit).toMatch(/vault\.keyImageFileFor\(/);
    expect(emit).toMatch(/expected \$\{each\.expect\} and wallet2 said/);
    const build = readFileSync('oracle/build.sh', 'utf8');
    expect(build).toContain('src/wallet/wallet2.cpp');
  });
});
