/*
 * The oracle is committed, and it is the same Monero as the vendored copy.
 *
 * ## What this guards
 *
 * A good part of this repository's Monero work is checked against numbers that
 * came out of Monero's own C++: the CryptoNight vectors, every ring signature
 * in the key-image export, the whole finished blob. Those numbers are only
 * worth anything if somebody can regenerate them, and until now the thing that
 * produced them lived in a git-ignored scratch directory. It was lost once,
 * between sessions, and had to be rebuilt from a fresh clone.
 *
 * That is the failure this file exists to stop repeating. `oracle/` is now
 * committed: a build recipe, five small harness sources, and a regenerator.
 * `./oracle/build.sh --check && node oracle/emit.mjs --check` rebuilds every
 * fixture from Monero at the pinned tag and diffs it against what is in the
 * tree, so "these came from Monero" is a claim a reviewer can run rather than
 * one they have to accept.
 *
 * ## What it deliberately does not do
 *
 * It does not run the oracle. That needs a Monero checkout and a C++ toolchain
 * with boost headers, and a suite which fetched half a gigabyte of upstream
 * C++ would be a suite people learn to skip — at which point the checking
 * stops happening at all. What runs here is cheap and catches the things that
 * actually drift: the pins disagreeing with each other, a harness going
 * missing, a fixture losing its provenance.
 */
import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';

const pinned: {
  upstream: string;
  tag: string;
  commit: string;
  produces: string[];
  bitcoin: {
    electrum: { repo: string; commit: string };
    bbqr: { repo: string; spec: string };
    produces: string[];
  };
} = JSON.parse(readFileSync('oracle/PINNED.json', 'utf8'));

const vendored: { upstream: string; tag: string; commit: string } = JSON.parse(
  readFileSync('vendor/cryptonight/MANIFEST.json', 'utf8'),
);

describe('the oracle rig', () => {
  it('pins the same Monero the app actually ships', () => {
    /* The load-bearing one. vendor/cryptonight is compiled into the app; the
     * oracle is what its fixtures were measured against. If those two drift
     * apart, every cross-language check in the repository is comparing one
     * version of Monero to another and calling the agreement a proof.
     *
     * `CryptoNightVectorTests.swift` asserts the vendored C reproduces the
     * fixture's chacha key, and that assertion is only meaningful while this
     * one holds. */
    expect(pinned.upstream).toBe(vendored.upstream);
    expect(pinned.tag).toBe(vendored.tag);
    expect(pinned.commit).toBe(vendored.commit);
    expect(pinned.commit).toMatch(/^[0-9a-f]{40}$/);
  });

  it('still has every piece the recipe needs', () => {
    /* Cheap, and it catches the thing that actually happened once: the rig
     * disappearing. A missing harness is not noticed by any other test,
     * because nothing in `npm test` compiles it. */
    for (const path of [
      'oracle/build.sh',
      'oracle/emit.mjs',
      'oracle/PINNED.json',
      'oracle/README.md',
      'oracle/src/cryptonight.c',
      'oracle/src/keyimage.cpp',
      'oracle/src/rng-counter.c',
      'oracle/src/mlock-stub.cpp',
      'oracle/src/unreachable.c',
      'oracle/src/shim/boost/preprocessor/stringize.hpp',
      'oracle/btc.sh',
      'oracle/btc-emit.mjs',
    ]) {
      expect(existsSync(path), `${path} is gone`).toBe(true);
    }
  });

  it('produces every fixture it claims to', () => {
    for (const path of pinned.produces) {
      expect(existsSync(path), `${path} is claimed but missing`).toBe(true);
      const fixture = JSON.parse(readFileSync(path, 'utf8'));
      /* The fixture has to name the same tag, or it predates the pin and
       * nobody would know. */
      expect(fixture.source?.tag, `${path} does not name its Monero tag`).toBe(pinned.tag);
      expect(fixture.note, `${path} does not say where it came from`).toMatch(/oracle\//);
    }
    expect(pinned.produces.length).toBeGreaterThan(0);
  });

  it('pins the Bitcoin wallets its fixtures were measured against', () => {
    /* The Bitcoin side is Python rather than C++, and for a while it had no
     * rig at all: the commits were recorded in a doc and the fixtures were
     * generated by hand. Same weakness as the Monero side had, same fix. */
    expect(pinned.bitcoin.electrum.commit).toMatch(/^[0-9a-f]{40}$/);
    expect(pinned.bitcoin.bbqr.repo).toContain('BBQr');
    for (const path of pinned.bitcoin.produces) {
      expect(existsSync(path), `${path} is claimed but missing`).toBe(true);
      const fixture = JSON.parse(readFileSync(path, 'utf8'));
      expect(fixture.note, `${path} does not say how to regenerate it`).toMatch(/oracle\/btc-emit/);
    }
  });

  it('records that the BBQr reference accepted our frames, not just that it exists', () => {
    /* The distinction the wallet-wires fixture turns on. Its `electrumBase43`
     * is Electrum's output and can simply be copied; its `bbqrFrames` are
     * *ours*, and the only thing that makes them worth anything is that
     * Coinkite's own joiner reassembled them into the original PSBT. So the
     * regenerator has to hand them over and check, and it exits non-zero if
     * they are refused. A version that copied the reference's own frames
     * instead would be testing nothing. */
    const emit = readFileSync('oracle/btc-emit.mjs', 'utf8');
    expect(emit).toContain('join_qrs');
    expect(emit).toMatch(/bbqrAccepted/);
    expect(emit).toMatch(/did NOT accept our frames/);
  });

  it('keeps the RNG stub, which is the only reason signatures are comparable', () => {
    /* Monero draws a nonce inside `generate_signature` and
     * `generate_ring_signature`. Two correct implementations of those produce
     * different bytes on the same input, so without a deterministic RNG there
     * is no fixture to write and nothing to compare the TypeScript against.
     *
     * If somebody ever "fixes" this stub to use real randomness, the fixtures
     * stop reproducing and the reason will not be obvious. */
    const stub = readFileSync('oracle/src/rng-counter.c', 'utf8');
    expect(stub).toContain('generate_random_bytes_thread_safe');
    expect(stub).toMatch(/counter\+\+|counter \+ i/);
  });

  it('builds the same CryptoNight the phone runs', () => {
    /* NO_AES picks the portable implementation out of the three inside
     * slow-hash.c. vendor/cryptonight ships that one, so the oracle has to
     * build it too — otherwise the fixtures are measured against a code path
     * the app never executes, and all three implementations agreeing on four
     * vectors is doing the work that a test was supposed to do. */
    const build = readFileSync('oracle/build.sh', 'utf8');
    expect(build).toContain('-DNO_AES');
    expect(build).toContain('-DFORCE_USE_HEAP');
    const defines = (JSON.parse(readFileSync('vendor/cryptonight/MANIFEST.json', 'utf8')) as {
      buildDefines: Record<string, string>;
    }).buildDefines;
    for (const define of Object.keys(defines)) {
      expect(build, `oracle/build.sh does not set ${define}, which the vendored build does`)
        .toContain(`-D${define}`);
    }
  });

  it('refuses to build against a Monero that is not the pinned one', () => {
    /* A tag can move, a mirror can lie, and a half-finished checkout looks
     * like a finished one. The recipe checks the commit it actually got. */
    const build = readFileSync('oracle/build.sh', 'utf8');
    expect(build).toContain('rev-parse HEAD');
    expect(build).toMatch(/refusing to build against a different Monero/);
  });
});
