/**
 * The sealed vault, tested the way the airgap wire was: against
 * implementations that share no code with ours.
 *
 * The two primitives are pinned to outside answers. Argon2id here is checked
 * against the reference C implementation (via argon2-cffi), and the AEAD
 * against libsodium; the vectors below were generated by running those, not by
 * running our own code and writing down what it said. A KDF that quietly
 * derived different keys than everyone else's would still round-trip its own
 * seals perfectly, and would strand every vault the day the app is
 * reinstalled from a build that does it right.
 *
 * The rest is about refusing: tampered bytes, wrong passphrases, hostile
 * parameters, truncation. A vault that opens for almost the right passphrase
 * is not a vault.
 */

import { describe, expect, it } from 'vitest';
import { argon2id } from '@noble/hashes/argon2.js';
import { xchacha20poly1305 } from '@noble/ciphers/chacha.js';
import {
  DEFAULT_KDF,
  KDF_LIMITS,
  calibrateKdf,
  looksSealed,
  passphraseToBytes,
  seal,
  unseal,
} from '../src/keys/seal';

const enc = (text: string) => new TextEncoder().encode(text);
const hex = (bytes: Uint8Array) => Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('');

/** Deterministic "randomness" for tests. Sealing itself demands real bytes. */
function fakeRandom(seed = 1): Uint8Array {
  const out = new Uint8Array(40);
  let x = seed >>> 0;
  for (let i = 0; i < out.length; i++) {
    x = (Math.imul(x, 1103515245) + 12345) >>> 0;
    out[i] = (x >>> 16) & 0xff;
  }
  return out;
}

/** Passphrases are bytes now. This is the one place a test turns text into
 *  them, so a call site that still passes a string does not typecheck. */
const pw = passphraseToBytes;

const SECRET = enc('a thirty-two byte secret, roughly');
const FAST = { t: 1, m: 8192, p: 1 }; // the smallest params this build accepts

describe('the primitives, against implementations that are not ours', () => {
  it('derives the same key as the Argon2 reference implementation', () => {
    // Generated with argon2-cffi (bindings to the reference C code).
    const got = argon2id(enc('correct horse battery staple'), enc('sixteen byte salt'), {
      t: 3, m: 8192, p: 1, dkLen: 32,
    });
    expect(hex(got)).toBe('2bfe6ca0ec5cbc6ce9006453956327aee67eea39a4c021bb0454d614bf25ca5b');

    const second = argon2id(enc('password'), enc('somesaltsomesalt'), { t: 2, m: 65536, p: 1, dkLen: 32 });
    expect(hex(second)).toBe('fc33b78139231d34b71626bd6245c1d72efa190ad605c3d8166a72adcedfa2c2');
  });

  it('encrypts exactly what libsodium encrypts', () => {
    // Generated with libsodium's crypto_aead_xchacha20poly1305_ietf_encrypt.
    const key = Uint8Array.from({ length: 32 }, (_, i) => i);
    const nonce = Uint8Array.from({ length: 24 }, (_, i) => 0xa0 + i);
    const ad = Uint8Array.from({ length: 8 }, (_, i) => 0x50 + i);
    const ct = xchacha20poly1305(key, nonce, ad).encrypt(enc('the vault seals thirty-two bytes'));
    expect(hex(ct)).toBe(
      '31846f3dc13cd1c0154f5eec105cd0e04fc2f65ede7fe7ad6a2fab859ed79b45f37dd9c8efc22fd1ed34f7bf5b90ad05',
    );
  });
});

describe('sealing and opening', () => {
  const sealed = seal(SECRET, pw('open sesame'), fakeRandom(), FAST);

  it('round-trips, and reports the parameters it was sealed under', () => {
    expect(sealed.ok).toBe(true);
    const opened = unseal(sealed.sealed!, pw('open sesame'));
    expect(opened.ok).toBe(true);
    expect(opened.secret).toEqual(SECRET);
    expect(opened.params).toEqual(FAST);
  });

  it('recognises its own blobs, for a file picker', () => {
    expect(looksSealed(sealed.sealed!)).toBe(true);
    expect(looksSealed(new Uint8Array([1, 2, 3]))).toBe(false);
    expect(looksSealed(enc('LVS but actually prose'))).toBe(false);
  });

  it('normalises the passphrase the way BIP39 does', () => {
    // The same passphrase composed two different ways by two keyboards must
    // open the same vault, or a person is locked out by their font.
    const composed = 'café';       // é as one code point
    const decomposed = 'café';    // e + combining accent
    const vault = seal(SECRET, pw(composed), fakeRandom(2), FAST);
    expect(unseal(vault.sealed!, pw(decomposed)).ok).toBe(true);
  });

  it('gives different bytes for the same secret sealed twice', () => {
    // Fresh salt and nonce per seal: two seals of the same secret share
    // nothing an observer can correlate.
    const again = seal(SECRET, pw('open sesame'), fakeRandom(99), FAST);
    expect(hex(again.sealed!)).not.toBe(hex(sealed.sealed!));
  });
});

describe('refusing, which is most of what a vault does', () => {
  const sealed = seal(SECRET, pw('open sesame'), fakeRandom(), FAST).sealed!;

  it('refuses the wrong passphrase, with the same words as a damaged file', () => {
    const wrongPass = unseal(sealed, pw('open sesame '));
    const damaged = unseal(
      (() => { const copy = sealed.slice(); copy[copy.length - 1]! ^= 1; return copy; })(),
      pw('open sesame'),
    );
    expect(wrongPass.ok).toBe(false);
    expect(damaged.ok).toBe(false);
    // Indistinguishable on purpose: no oracle for which of the two it was.
    expect(wrongPass.problem).toBe(damaged.problem);
  });

  it('fails closed for a flip of any single byte, header or body', { timeout: 60_000 }, () => {
    /* The whole blob, one byte at a time — about a hundred unseals, each
     * paying the full KDF, which is why this test gets a long timeout instead
     * of a smaller sweep. The header bytes are the point: they are
     * authenticated as associated data, so an attacker cannot keep the
     * ciphertext and rewrite the KDF parameters around it. */
    for (let i = 0; i < sealed.length; i++) {
      const copy = sealed.slice();
      copy[i]! ^= 0x01;
      const result = unseal(copy, pw('open sesame'));
      expect(result.ok, `byte ${i} flipped and it still opened`).toBe(false);
    }
  });

  it('refuses truncation at every length', () => {
    for (let n = 0; n < sealed.length; n++) {
      expect(unseal(sealed.subarray(0, n), pw('open sesame')).ok, `${n} bytes`).toBe(false);
    }
  });

  it('refuses a version from the future', () => {
    const future = sealed.slice();
    future[3] = 2;
    expect(unseal(future, pw('open sesame')).problem).toMatch(/newer version/i);
  });

  it('refuses to seal weakly or emptily', () => {
    expect(seal(SECRET, pw('pass'), fakeRandom(), { t: 1, m: 64, p: 1 }).ok, 'trivial memory').toBe(false);
    expect(seal(SECRET, pw(''), fakeRandom(), FAST).problem, 'empty passphrase').toMatch(/passphrase/i);
    expect(seal(new Uint8Array(0), pw('pass'), fakeRandom(), FAST).ok, 'empty secret').toBe(false);
    expect(seal(SECRET, pw('pass'), fakeRandom().subarray(0, 39), FAST).ok, 'short randomness').toBe(false);
  });

  it('refuses hostile KDF parameters before allocating for them', () => {
    /* A scanned file claiming a 4 GiB memory cost would take the phone down
     * before the tag was ever checked, because the allocation comes first.
     * The ceiling has to be enforced on the claim, not the result. */
    const hostile = sealed.slice();
    new DataView(hostile.buffer).setUint32(5, 0x40000000, false); // ~1 TiB in KiB
    const result = unseal(hostile, pw('open sesame'));
    expect(result.ok).toBe(false);
    expect(result.problem).toMatch(/will not run/i);
  });
});

describe('calibration', () => {
  it('walks memory up until the target time is met', () => {
    /* The walk starts at the default and climbs; a device that reaches the
     * target only at 256 MiB should be given 256 MiB. */
    let now = 0;
    const params = calibrateKdf(
      250,
      () => now,
      (p) => { now += p.m >= 262144 ? 300 : 100; },
    );
    expect(params.m).toBe(262144);
    expect(params.t).toBe(DEFAULT_KDF.t);
  });

  it('stops at the ceiling rather than climbing forever', () => {
    let now = 0;
    const params = calibrateKdf(1e9, () => now, () => { now += 1; });
    expect(params.m).toBe(KDF_LIMITS.maxM);
  });
});

describe('calibration can only strengthen', () => {
  it('never returns parameters weaker than the default it replaces', () => {
    /* The audit finding: the walk used to start at the floor, so on a device
     * too slow to reach the target — exactly the old phone this app is for —
     * calling the tuning function produced an 8 MiB vault where doing nothing
     * would have produced 64 MiB. A function whose purpose is to make the
     * vault harder to open must never make it easier. */
    let now = 0;
    const slow = calibrateKdf(1000, () => now, () => { now += 5000; });
    expect(slow.m).toBeGreaterThanOrEqual(DEFAULT_KDF.m);
    expect(slow.t).toBe(DEFAULT_KDF.t);
  });

  it('still climbs on a device that can afford more', () => {
    let now = 0;
    const fast = calibrateKdf(250, () => now, (p) => { now += p.m >= 262144 ? 300 : 10; });
    expect(fast.m).toBe(262144);
  });
});
