/**
 * BC-UR, checked frame-for-frame against the reference implementation.
 *
 * This is the file that decides whether the vault can talk to Sparrow,
 * Electrum, Keystone and Cupcake, or only to itself. Interop cannot be tested
 * by round-tripping our own encoder through our own decoder: that passes
 * happily with a wrong bytewords table, a swapped pair of random draws, or a
 * fragment length computed one way rather than another. Every one of those
 * produces frames that look like UR, decode with our own reader, and are
 * silently unreadable by everybody else, or worse, readable as something
 * different.
 *
 * So the fixtures in test/fixtures/ur-vectors.json were generated by running
 * @ngraveio/bc-ur, and the tests below assert on its exact output: the same
 * strings, character for character, and the same fragment indexes for the same
 * frame numbers.
 */

import { describe, expect, it } from 'vitest';
import { chooseDegree, chooseFragments, shuffle, Xoshiro } from '../src/airgap/fountain';
import { cborEncode } from '../src/airgap/cbor';
import { bytewordsDecode } from '../src/airgap/bytewords';
import {
  UrCollector,
  UrEncoder,
  encodeUr,
  nominalFragmentLength,
  parseUr,
  urPayloadBytes,
} from '../src/airgap/ur';
import vectors from './fixtures/ur-vectors.json';

const bin = (text: string): Uint8Array =>
  new Uint8Array((text.match(/../g) ?? []).map((pair) => parseInt(pair, 16)));

/** The same deterministic bytes the fixture generator used. */
function bytes(n: number, seed: number): Uint8Array {
  const out = new Uint8Array(n);
  let x = seed >>> 0;
  for (let i = 0; i < n; i++) {
    x = (Math.imul(x, 1103515245) + 12345) >>> 0;
    out[i] = (x >>> 16) & 0xff;
  }
  return out;
}

function collect(frames: string[]): Uint8Array | null {
  const collector = new UrCollector();
  for (const frame of frames) {
    const progress = collector.offer(frame);
    if (progress.cbor) return progress.cbor;
  }
  return null;
}

describe('the fountain, which both sides have to derive identically', () => {
  it('picks the same fragments as the reference for every frame it was asked about', () => {
    /* 405 combinations of frame number, fragment count and checksum. If this
     * passes, our xoshiro, our sha256, our alias tables and our shuffle all
     * agree with the implementation the other wallets are running. If one bit
     * of any of them were wrong, mixed frames would decode to plausible
     * rubbish with every checksum on the outside intact. */
    for (const [seqNum, seqLength, checksum, expected] of vectors.chooseFragments as Array<
      [number, number, number, number[]]
    >) {
      expect(chooseFragments(seqNum, seqLength, checksum), `${seqNum} of ${seqLength}`).toEqual(
        expected,
      );
    }
  });

  it('makes the first pass plain fragments in order', () => {
    // The property that lets a receiver decode without ever touching the
    // mixing code, as long as it catches a clean first pass.
    for (let i = 1; i <= 20; i++) expect(chooseFragments(i, 20, 0xdeadbeef)).toEqual([i - 1]);
  });

  it('draws degrees in the range the distribution allows', () => {
    const rng = new Xoshiro(new Uint8Array([1, 2, 3, 4]));
    for (let i = 0; i < 200; i++) {
      const degree = chooseDegree(9, rng);
      expect(degree).toBeGreaterThanOrEqual(1);
      expect(degree).toBeLessThanOrEqual(9);
    }
  });

  it('shuffles without losing or duplicating anything', () => {
    const rng = new Xoshiro(new Uint8Array([9]));
    for (let n = 1; n < 30; n++) {
      const items = [...new Array(n)].map((_, i) => i);
      const shuffled = shuffle(items, rng);
      expect([...shuffled].sort((a, b) => a - b)).toEqual(items);
    }
  });
});

describe('splitting a message the way BC-UR splits it', () => {
  it('makes every fragment the same size, which is what lets them be XORed', () => {
    // Not "fill 100 then whatever is left": the counts are walked upward until
    // one divides the message into equal pieces small enough to fit.
    expect(nominalFragmentLength(303, 60)).toBe(51);
    expect(nominalFragmentLength(2603, 100)).toBe(97);
    expect(nominalFragmentLength(100, 100)).toBe(100);
    expect(nominalFragmentLength(101, 100)).toBe(51);
  });
});

describe('writing frames a hardware wallet will read', () => {
  it('writes a short message as one frame, with no sequence number', () => {
    const payload = bin(vectors.single.payloadHex);
    expect(encodeUr('crypto-psbt', payload, 500).nextPart()).toBe(vectors.single.ur);
  });

  it('writes the same 40 frames as the reference, character for character', () => {
    const encoder = encodeUr('crypto-psbt', bin(vectors.mid.payloadHex), vectors.mid.maxFragmentLength);
    expect(encoder.seqLength).toBe(vectors.mid.seqLength);
    for (const expected of vectors.mid.frames) expect(encoder.nextPart()).toBe(expected);
  });

  it('agrees on a longer message too, well past the first pass', () => {
    // 27 fragments and 90 frames, so most of what is asserted here is mixed
    // frames rather than plain ones.
    const encoder = encodeUr('crypto-psbt', bin(vectors.big.payloadHex), vectors.big.maxFragmentLength);
    expect(encoder.seqLength).toBe(vectors.big.seqLength);
    for (const expected of vectors.big.frames) expect(encoder.nextPart()).toBe(expected);
  });

  it('refuses a type name that is not a UR type', () => {
    expect(() => new UrEncoder('Crypto-PSBT', cborEncode(new Uint8Array(4)))).toThrow(/not a UR type/);
    expect(() => new UrEncoder('crypto psbt', cborEncode(new Uint8Array(4)))).toThrow(/not a UR type/);
  });
});

describe('reading frames a hardware wallet wrote', () => {
  it('reads a single-frame message', () => {
    const collector = new UrCollector();
    const progress = collector.offer(vectors.single.ur);
    expect(progress.type).toBe('crypto-psbt');
    expect(urPayloadBytes(progress.cbor!)).toEqual(bin(vectors.single.payloadHex));
  });

  it('reads a clean first pass', () => {
    const first = vectors.mid.frames.slice(0, vectors.mid.seqLength);
    expect(urPayloadBytes(collect(first)!)).toEqual(bin(vectors.mid.payloadHex));
  });

  it('reads it out of order and repeated, which is how a camera sees it', () => {
    const first = vectors.mid.frames.slice(0, vectors.mid.seqLength);
    const messy = [...first].reverse().flatMap((frame) => [frame, frame, first[0]!]);
    expect(urPayloadBytes(collect(messy)!)).toEqual(bin(vectors.mid.payloadHex));
  });

  it('recovers fragments it never saw plainly, out of the mixed frames', () => {
    /* The reason for all of the above. Three of the plain frames are dropped,
     * as a camera drops them, and the message still assembles: each missing
     * fragment is peeled out of a later XOR of several. Without the fountain
     * code this scan would never finish, because a UR animation does not
     * come back round to frame 2. */
    const dropped = new Set([2, 5, 19]);
    const frames = vectors.big.frames.filter((_, i) => !dropped.has(i + 1));
    const assembled = collect(frames);
    expect(assembled, 'the peeling has to complete').not.toBeNull();
    expect(urPayloadBytes(assembled!)).toEqual(bin(vectors.big.payloadHex));
  });

  it('reports progress so a person knows to keep filming', () => {
    const collector = new UrCollector();
    const first = collector.offer(vectors.mid.frames[0]!);
    expect(first.cbor).toBeNull();
    expect(first.have).toBe(1);
    expect(first.total).toBe(vectors.mid.seqLength);
    expect(collector.offer(vectors.mid.frames[1]!).have).toBe(2);
  });

  it('ignores everything else a camera sees', () => {
    for (const junk of ['', 'WIFI:S:home;', 'https://example.com', 'ur:', 'ur:crypto-psbt']) {
      expect(parseUr(junk), junk).toBeNull();
    }
    const collector = new UrCollector();
    expect(collector.offer('bitcoin:bc1qexample').problem).toMatch(/not a UR code/i);
  });
});

describe('refusing to assemble the wrong thing', () => {
  it('refuses a frame whose bytewords did not read cleanly', () => {
    const frame = vectors.mid.frames[0]!;
    const body = frame.split('/')[2]!;
    const damaged = frame.replace(body, (body[0] === 'a' ? 'b' : 'a') + body.slice(1));
    expect(parseUr(damaged), 'the bytewords checksum catches it').toBeNull();
  });

  it('refuses a frame whose two headers disagree', () => {
    /* The sequence number appears twice: once in the path, once inside the
     * CBOR. They are written by the same encoder, so a disagreement means one
     * of them was misread, and neither can be trusted after that. */
    const frame = vectors.mid.frames[1]!;
    const lying = frame.replace('/2-6/', '/3-6/');
    expect(parseUr(lying)).toBeNull();
  });

  it('refuses impossible sequence numbers', () => {
    const body = vectors.mid.frames[0]!.split('/')[2]!;
    expect(parseUr(`ur:crypto-psbt/0-6/${body}`)).toBeNull();
    expect(parseUr(`ur:crypto-psbt/1-0/${body}`)).toBeNull();
    expect(parseUr(`ur:crypto-psbt/1/${body}`)).toBeNull();
    expect(parseUr(`ur:crypto-psbt/1-6/extra/${body}`)).toBeNull();
  });

  it('starts again rather than merging two different messages', () => {
    /* Somebody scans half a transaction and then points the camera at a
     * different one with the same fragment count. Merging them would assemble
     * a valid-looking hybrid of two transactions, which is the exact failure
     * this whole layer exists to prevent. */
    const other = encodeUr('crypto-psbt', bytes(300, 99), vectors.mid.maxFragmentLength);
    const collector = new UrCollector();
    collector.offer(vectors.mid.frames[0]!);
    collector.offer(vectors.mid.frames[1]!);
    const otherFrames = other.firstPass();
    expect(collector.offer(otherFrames[0]!).have, 'the count starts over').toBe(1);
    for (const frame of otherFrames.slice(1)) collector.offer(frame);
    expect(urPayloadBytes(collector.status().cbor!)).toEqual(bytes(300, 99));
  });

  it('does not accept a fragment from a message of a different length', () => {
    const collector = new UrCollector();
    collector.offer(vectors.big.frames[0]!);
    const before = collector.status().have;
    // A frame of the mid message, which has a different checksum and length.
    collector.offer(vectors.mid.frames[1]!);
    expect(collector.status().have).toBe(before);
  });
});

describe('our own frames, our own reader', () => {
  it('round-trips payloads of every awkward size', () => {
    for (const size of [1, 2, 99, 100, 101, 1000, 4096]) {
      const payload = bytes(size, size);
      const frames = encodeUr('crypto-psbt', payload, 100).firstPass();
      expect(urPayloadBytes(collect(frames)!), `${size} bytes`).toEqual(payload);
    }
  });

  it('carries a payload the size of a Monero transaction set', () => {
    const payload = bytes(40_000, 3);
    const encoder = encodeUr('xmr-txunsigned', payload, 400);
    expect(encoder.seqLength).toBeGreaterThan(90);
    const assembled = collect(encoder.firstPass());
    expect(urPayloadBytes(assembled!)).toEqual(payload);
  });

  it('keeps the type name, so the vault knows what it was handed', () => {
    const collector = new UrCollector();
    collector.offer(encodeUr('crypto-account', bytes(40, 5), 500).nextPart());
    expect(collector.status().type).toBe('crypto-account');
  });
});

describe('bounds on a single frame', () => {
  /* Thirty seconds, not vitest's default five. The assertion here is
   * relative and so is immune to a busy machine, but the *raw* leg of the
   * comparison deliberately decodes forty megabytes of bytewords with no cap
   * in front of it — that is the work being measured — and on a loaded runner
   * it can take longer than the default allows. A timeout is not a signal
   * about the property under test, so it should not be able to fail it. */
  it('refuses an oversized single-part body without doing the work first', { timeout: 30_000 }, () => {
    /* The cap is a denial-of-service guard, not a correctness guard: an
     * oversized body decodes to null either way, because it fails its
     * checksum. The return value cannot tell you whether the cap is there —
     * the first version of this test asserted only the null and passed with
     * the cap deleted.
     *
     * So the work avoided is measured. An absolute millisecond bound was the
     * obvious next move and it flaked the moment the suite got busier, so the
     * comparison is relative instead: the same input, through the capped path
     * and through the decoder the cap is protecting. Both feel the same
     * machine, so load cancels out.
     *
     * 'aa' rather than random letters because it is a real minimal pair, so
     * nothing short-circuits early on an unknown word. */
    const huge = 'aa'.repeat(20_000_000);

    const cappedStart = performance.now();
    expect(parseUr(`ur:bytes/${huge}`)).toBeNull();
    const capped = performance.now() - cappedStart;

    const rawStart = performance.now();
    expect(bytewordsDecode(huge, 'minimal')).toBeNull();
    const raw = performance.now() - rawStart;

    expect(raw, 'the unguarded decode should be slow enough to be worth guarding').toBeGreaterThan(100);
    expect(capped * 20, `capped ${capped.toFixed(1)}ms vs raw ${raw.toFixed(1)}ms`).toBeLessThan(raw);
  });
});
