/*
 * The two wires that are not BC-UR, against the wallets' own code.
 *
 * `test/fixtures/wallet-wires.json` was not generated by this repository. The
 * base43 strings are the output of Electrum's own `electrum.bitcoin.base_encode`,
 * and the frames under `referenceFrames*` are the output of Coinkite's own
 * BBQr `split_qrs`. Our frames in `bbqrFrames` are ours, and every one of them
 * was fed to Coinkite's `join_qrs` and came back as the original PSBT before
 * the file was written. The PSBTs are the BBQr project's test corpus, which
 * has the useful property of containing a transaction nobody here designed.
 *
 * That matters more here than it does for a hash. There is no specification to
 * appeal to for either format — base43 is whatever `bitcoin.py` does, and BBQr
 * is a page on bbqr.info plus an implementation. So "correct" means "the wallet
 * accepts it", and the only honest way to test that is to have asked the wallet.
 *
 * ## Why these two formats exist at all
 *
 * Electrum has no BC-UR of any kind: no `crypto-psbt`, no fountain decoder,
 * nothing. It reads one static QR of base43, and that is the entire camera
 * surface. Coldcard has no BC-UR either; it reads BBQr. Both were named on the
 * app's wire picker while it emitted only UR, which is the defect this test
 * exists to keep fixed.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { base43Encode, base43Decode, base43Frame, MAX_ALPHANUMERIC_QR_CHARS } from '../src/airgap/base43';
import { bbqrEncode, bbqrDecode, bbqrParsePart, BBQR_BODY_CHARS } from '../src/airgap/bbqr';

interface Vector {
  name: string;
  bytes: number;
  psbtHex: string;
  electrumBase43: string;
  fitsOneQr: boolean;
  bbqrFrames: string[];
  referenceFramesBase32?: string[];
  referenceFramesHex?: string[];
}

const fixture: { vectors: Vector[] } = JSON.parse(
  readFileSync('test/fixtures/wallet-wires.json', 'utf8'),
);

const bytes = (hex: string) =>
  Uint8Array.from(hex.match(/../g)!.map((pair) => parseInt(pair, 16)));
const hex = (b: Uint8Array) => Array.from(b, (x) => x.toString(16).padStart(2, '0')).join('');

describe('base43, which is the only thing Electrum reads from a camera', () => {
  it('produces exactly what Electrum produces', () => {
    /* Byte-identical, not merely acceptable. Electrum will take several
     * encodings, so "it parsed" would pass even if we emitted something in a
     * different format by accident; matching the string means we are on the
     * path Electrum's own QR export uses. */
    for (const v of fixture.vectors) {
      expect(base43Encode(bytes(v.psbtHex)), `${v.name} does not match Electrum`)
        .toBe(v.electrumBase43);
    }
  });

  it('reads back what Electrum wrote', () => {
    for (const v of fixture.vectors) {
      expect(hex(base43Decode(v.electrumBase43)!), `${v.name} did not survive the round trip`)
        .toBe(v.psbtHex);
    }
  });

  it('carries leading zero bytes rather than losing them in the integer', () => {
    /* A PSBT starts with `psbt\xff` so this never bites in production, which
     * is exactly why it would go unnoticed. Electrum's `base_encode` maps each
     * leading zero byte to one leading '0'; a big-int conversion that skipped
     * that step agrees on every real input and disagrees here. */
    const leading = Uint8Array.from([0, 0, 0, 1, 2, 3]);
    const encoded = base43Encode(leading);
    expect(encoded.startsWith('000')).toBe(true);
    expect(base43Decode(encoded)).toEqual(leading);
    expect(base43Decode(base43Encode(new Uint8Array(4)))).toEqual(new Uint8Array(4));
  });

  it('refuses a character that is not in the alphabet instead of skipping it', () => {
    /* This decodes what a camera resolved. Dropping an unreadable symbol and
     * carrying on would yield bytes that still parse as a transaction and are
     * not the transaction on the other screen. */
    expect(base43Decode('ABC!DEF')).toBeNull();
    expect(base43Decode('abc')).toBeNull(); // lower case is not the alphabet
  });

  it('says no when the PSBT cannot fit one QR, because Electrum has no second frame', () => {
    for (const v of fixture.vectors) {
      const frame = base43Frame(bytes(v.psbtHex));
      if (v.fitsOneQr) {
        expect(frame, `${v.name} should fit`).not.toBeNull();
        expect(frame).toHaveLength(1);
        expect(frame![0]!.length).toBeLessThanOrEqual(MAX_ALPHANUMERIC_QR_CHARS);
      } else {
        expect(frame, `${v.name} does not fit a QR and must not be offered`).toBeNull();
      }
    }
    /* The corpus has to actually contain both cases or this asserts nothing. */
    expect(fixture.vectors.some((v) => v.fitsOneQr)).toBe(true);
    expect(fixture.vectors.some((v) => !v.fitsOneQr)).toBe(true);
  });
});

describe('BBQr, which is the only thing Coldcard reads from a camera', () => {
  it('emits the frames Coinkite’s own joiner accepted', () => {
    for (const v of fixture.vectors) {
      expect(bbqrEncode(bytes(v.psbtHex), 'P'), `${v.name} frames changed`)
        .toEqual(v.bbqrFrames);
    }
  });

  it('reads the frames Coinkite’s own splitter wrote, in both encodings', () => {
    /* The other direction, and the one that matters when a Coldcard or a
     * Sparrow is the sender. `H` is in here as well as `2` because the spec
     * makes both mandatory for receivers even though a sender picks one. */
    let checked = 0;
    for (const v of fixture.vectors) {
      for (const frames of [v.referenceFramesBase32, v.referenceFramesHex]) {
        if (!frames) continue;
        const decoded = bbqrDecode(frames);
        expect(decoded, `${v.name} reference frames did not decode`).not.toBeNull();
        expect(decoded!.type).toBe('P');
        expect(hex(decoded!.bytes)).toBe(v.psbtHex);
        checked++;
      }
    }
    expect(checked, 'the fixture carries no reference frames').toBeGreaterThanOrEqual(6);
  });

  it('writes a header the spec would recognise', () => {
    const frames = bbqrEncode(bytes(fixture.vectors[0]!.psbtHex), 'P')!;
    expect(frames[0]!.slice(0, 4)).toBe('B$2P');
    for (const [i, frame] of frames.entries()) {
      const part = bbqrParsePart(frame)!;
      expect(part.parts).toBe(frames.length);
      expect(part.index).toBe(i);
      expect(part.encoding).toBe('2');
    }
  });

  it('keeps every frame the same length but the last, on the 8-character grid', () => {
    /* Both halves are load-bearing. Equal length is what lets a receiver size
     * its buffer from any frame except the runt; the multiple of eight is what
     * makes each frame decode to whole bytes, which BBQr requires and a
     * conforming receiver is entitled to enforce. */
    const big = fixture.vectors.find((v) => v.bytes > 4000)!;
    const frames = bbqrEncode(bytes(big.psbtHex), 'P')!;
    expect(frames.length).toBeGreaterThan(2);
    const bodies = frames.map((f) => f.length - 8);
    for (const body of bodies.slice(0, -1)) {
      expect(body).toBe(BBQR_BODY_CHARS);
      expect(body % 8).toBe(0);
    }
    expect(bodies.at(-1)!).toBeLessThanOrEqual(BBQR_BODY_CHARS);
  });

  it('uses only characters a QR can put in alphanumeric mode', () => {
    /* The entire reason for base32 over base64. One character outside this set
     * silently drops the QR into byte mode, every frame gets bigger, and
     * nothing fails — it just becomes a worse product. */
    const alnum = /^[0-9A-Z$%*+\-./: ]+$/;
    for (const v of fixture.vectors) {
      for (const frame of bbqrEncode(bytes(v.psbtHex), 'P')!) {
        expect(alnum.test(frame), `${v.name} frame leaves alphanumeric mode`).toBe(true);
      }
    }
  });

  it('refuses a series it cannot honestly reassemble', () => {
    const frames = bbqrEncode(bytes(fixture.vectors[1]!.psbtHex), 'P')!;
    expect(frames.length).toBeGreaterThan(2);

    expect(bbqrDecode(frames.slice(0, -1)), 'a short series decoded').toBeNull();
    expect(bbqrDecode([]), 'nothing decoded to something').toBeNull();

    /* Two different bodies claiming the same slot means two messages got
     * mixed in front of the camera. Picking one is a coin flip over what gets
     * signed, so neither is picked.
     *
     * Note the shape: the conflicting frame is *added* to a complete series,
     * not substituted into it. The first version of this test substituted, and
     * passed nothing — one frame with a corrupted body is not a collision, it
     * is just wrong data, and this layer cannot tell. BBQr has no checksum by
     * design, on the reasoning that a QR symbol carries its own error
     * correction and one that resolves resolves correctly. What stands between
     * a mangled PSBT and a signature is the confirmation screen, which is
     * where it stands for every other wire here too. */
    expect(bbqrDecode([...frames, frames[1]!.slice(0, 8) + frames[2]!.slice(8)])).toBeNull();

    /* An exact duplicate is just the camera seeing a frame twice. */
    expect(bbqrDecode([...frames, frames[0]!])).not.toBeNull();

    /* Headers that are not ours. */
    expect(bbqrParsePart('B$2Z0100xyz'), 'unknown file type accepted').toBeNull();
    expect(bbqrParsePart('XX2P0100AAAA'), 'wrong magic accepted').toBeNull();
    expect(bbqrParsePart('B$2P0102AAAA'), 'index past the end accepted').toBeNull();
  });

  it('refuses the deflate encoding rather than returning compressed bytes', () => {
    /* `Z` is legal BBQr and receivers are meant to implement it. This one does
     * not, because a DEFLATE implementation is a new dependency or several
     * hundred lines whose bugs would look exactly like a camera misread. The
     * failure has to be a refusal: handing back the compressed blob as if it
     * were a PSBT is the outcome worth ruling out. */
    const zFrames = ['B$ZP0100AAAAAAAA'];
    expect(bbqrDecode(zFrames)).toBeNull();
  });
});
