/*
 * Regenerate the fixtures that came out of Monero's own crypto.
 *
 *   ./oracle/build.sh && node oracle/emit.mjs           write them
 *   node oracle/emit.mjs --check                        compare, change nothing
 *
 * `--check` is the one that matters. It rebuilds every fixture from the
 * harness and diffs against what is committed, so the claim "these numbers
 * came from Monero" stops being a sentence in a comment and becomes something
 * a reviewer can run. It is deliberately not part of `npm test`: that would
 * make the suite depend on a Monero checkout and a C++ toolchain, and a suite
 * with a heavy optional step is a suite people learn to skip.
 *
 * ## Why the inputs are what they are
 *
 * The keys are counted-up bytes rather than anything random. Two reasons, and
 * the second is the real one:
 *
 *   - a fixture regenerated from a fresh random key would differ every run,
 *     which makes `--check` impossible;
 *   - the RNG inside Monero is stubbed to a byte counter (oracle/src/rng-counter.c)
 *     so that `generate_signature` and `generate_ring_signature` are
 *     reproducible at all. Signatures draw a nonce; two correct
 *     implementations of the same signature scheme disagree byte for byte
 *     unless they are handed the same one. The counter is what lets the
 *     TypeScript be compared to the C rather than merely believed alongside it.
 *
 * None of these keys is secret and none should ever be used for anything. They
 * are test vectors.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';

const PINNED = JSON.parse(readFileSync('oracle/PINNED.json', 'utf8'));
const KEYIMAGE = 'oracle/.work/keyimage';

if (!existsSync(KEYIMAGE)) {
  console.error('oracle: no harness. Run ./oracle/build.sh first.');
  process.exit(1);
}

const check = process.argv.includes('--check');

/* The counter the RNG stub produces, so the nonces the C consumed can be
 * handed to the TypeScript. Draw order inside the harness is: one 32-byte
 * scalar per ring signature, then the 8-byte ChaCha IV, then one 32-byte
 * scalar for the outer signature. Getting that order wrong shows up
 * immediately as a signature mismatch, which is why it is not commented as an
 * assumption but exercised by the fixture itself. */
const counter = (start, n) =>
  Buffer.from(Array.from({ length: n }, (_, i) => (start + i) & 0xff)).toString('hex');

const VIEW_SECRET = '0e0d0c0b0a090807060504030201000f0e0d0c0b0a0908070605040302010001';
const SPEND_SECRET = '1a1b1c1d1e1f202122232425262728292a2b2c2d2e2f30313233343536373801';
const EPHEMERAL = [
  '0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f00',
  'a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebf00',
];

/** One run of the harness, parsed into the fields it prints. */
function run(offset, ephemerals) {
  const out = execFileSync(KEYIMAGE, [VIEW_SECRET, SPEND_SECRET, String(offset), ...ephemerals], {
    encoding: 'utf8',
  });
  const fields = {};
  const lists = { out_pub: [], key_image: [], ring_sig: [] };
  for (const line of out.split('\n')) {
    if (!line.trim()) continue;
    const [key, value] = [line.slice(0, line.indexOf(' ')), line.slice(line.indexOf(' ') + 1)];
    if (key in lists) lists[key].push(value);
    else fields[key] = value;
  }
  return { ...fields, ...lists };
}

const cases = [
  { name: 'empty', offset: 0, ephemerals: [] },
  { name: 'two', offset: 7, ephemerals: EPHEMERAL },
].map(({ name, offset, ephemerals }) => {
  const r = run(offset, ephemerals);
  const images = ephemerals.length;
  const nonces = Array.from({ length: images }, (_, i) => counter(32 * i, 32));
  nonces.push(counter(32 * images + 8, 32)); // after the IV
  return {
    name,
    offset,
    viewPublic: r.view_pub,
    spendPublic: r.spend_pub,
    chachaKey: r.chacha_key,
    outPubs: r.out_pub,
    keyImages: r.key_image,
    ringSigs: r.ring_sig,
    nonces,
    iv: r.iv,
    plaintext: r.plaintext,
    file: r.file,
  };
});

const fixture = {
  note:
    "Generated by Monero's own crypto, not by this repository. Regenerate with " +
    './oracle/build.sh && node oracle/emit.mjs, and check with --check. ' +
    'oracle/src/keyimage.cpp links crypto.cpp, crypto-ops.c and chacha.c from the tag ' +
    'below, with generate_random_bytes_thread_safe stubbed to a byte counter so the ' +
    'signatures are reproducible. The nonces are what that counter produced, and are ' +
    'fed to the TypeScript so the two can be compared byte for byte.',
  source: { repo: PINNED.upstream, tag: PINNED.tag },
  viewSecret: VIEW_SECRET,
  spendSecret: SPEND_SECRET,
  ephemeralSecrets: EPHEMERAL,
  cases,
};

// ---------------------------------------------------------------------------
// The unsigned transaction set
//
// This harness prints two things: the bytes Monero's own binary archive
// produced, and a JSON description of what went in. The TypeScript has to turn
// the first into the second, which is a stronger check than a round trip: a
// round trip only proves a reader and a writer agree with each other.

const UNSIGNED = 'oracle/.work/unsignedtxset';
let unsignedFixture = null;
if (existsSync(UNSIGNED)) {
  const printed = execFileSync(UNSIGNED, [], { encoding: 'utf8', maxBuffer: 16 * 1024 * 1024 });
  unsignedFixture = {
    note:
      "Generated by Monero's own binary archive, not by this repository. " +
      'oracle/src/unsignedtxset.cpp includes wallet/wallet2.h and serializes the real ' +
      'wallet2::unsigned_tx_set, so none of the layout is transcribed. `archive` is what ' +
      'binary_archive<true> wrote; `meaning` is what was put in. Regenerate with ' +
      './oracle/build.sh && node oracle/emit.mjs, and check with --check.',
    source: { repo: PINNED.upstream, tag: PINNED.tag },
    archive: /^archive (.+)$/m.exec(printed)[1],
    /* The whole file as `dump_tx_to_str` writes it: the prefix, then the
     * archive inside `encrypt_with_view_secret_key`. Same envelope as the
     * key-image export. */
    viewSecret: /^viewSecret (.+)$/m.exec(printed)[1],
    chachaKey: /^chachaKey (.+)$/m.exec(printed)[1],
    file: /^file (.+)$/m.exec(printed)[1],
    meaning: JSON.parse(/^meaning (.+)$/m.exec(printed)[1]),
  };
} else {
  console.error('oracle: no unsignedtxset harness; run ./oracle/build.sh');
  process.exit(1);
}

const outputs = [
  ['test/fixtures/monero-keyimages.json', fixture],
  ['test/fixtures/monero-unsigned-tx-set.json', unsignedFixture],
];

let anyDiffered = false;
for (const [PATH, value] of outputs) {
  const text = JSON.stringify(value, null, 2) + '\n';

  if (!check) {
    writeFileSync(PATH, text);
    console.log(`oracle: wrote ${PATH}`);
    continue;
  }

  const committed = readFileSync(PATH, 'utf8');
  if (committed === text) {
    console.log(`oracle: ${PATH} reproduces exactly from Monero ${PINNED.tag}`);
    continue;
  }
  anyDiffered = true;
  if (PATH.endsWith('monero-unsigned-tx-set.json')) {
    const a = JSON.parse(committed);
    if (a.archive !== value.archive) console.error('oracle: the archive bytes differ');
    if (JSON.stringify(a.meaning) !== JSON.stringify(value.meaning)) {
      console.error('oracle: the meaning differs');
    }
    console.error(`oracle: ${PATH} does NOT reproduce. Do not re-pin without knowing why.`);
    continue;
  }
  diffKeyImages(JSON.parse(committed), value, PATH);
}
process.exit(anyDiffered ? 1 : 0);

function diffKeyImages(a, b, PATH) {

  /* A field-level diff rather than "they differ", because the useful question
   * is always which value moved. */
  for (const [i, want] of a.cases.entries()) {
    const got = b.cases[i];
    for (const key of Object.keys(want)) {
      if (JSON.stringify(want[key]) !== JSON.stringify(got?.[key])) {
        console.error(`oracle: case ${want.name}: ${key} differs`);
        console.error(`  committed ${JSON.stringify(want[key]).slice(0, 96)}`);
        console.error(`  oracle    ${JSON.stringify(got?.[key]).slice(0, 96)}`);
      }
    }
  }
  console.error(`oracle: ${PATH} does NOT reproduce. Do not re-pin without knowing why.`);
}
