//  BundleDigest.swift
//  Generated by scripts/build-bundle.mjs. Do not edit.
//
//  The SHA-256 of the JavaScript this build is allowed to run. Engine.swift
//  hashes the file it loaded and refuses to evaluate anything that does not
//  match. Rebuild with `npm run build:bundle` rather than editing this.

enum BundleDigest {
    static let sha256 = "0f324bc30eb957ec28ed43f7c8a0b0de3988ea031ab38d94d26510f1e8bccb86"
}
