//  BundleDigest.swift
//  Generated by scripts/build-bundle.mjs. Do not edit.
//
//  The SHA-256 of the JavaScript this build is allowed to run. Engine.swift
//  hashes the file it loaded and refuses to evaluate anything that does not
//  match. Rebuild with `npm run build:bundle` rather than editing this.

enum BundleDigest {
    static let sha256 = "ba603e783ea1fa2cf8011042e684bc2732e930c7e237af481f6578a017cd0c40"
}
