//  BundleDigest.swift
//  Generated by scripts/build-bundle.mjs. Do not edit.
//
//  The SHA-256 of the JavaScript this build is allowed to run. Engine.swift
//  hashes the file it loaded and refuses to evaluate anything that does not
//  match. Rebuild with `npm run build:bundle` rather than editing this.

enum BundleDigest {
    static let sha256 = "5f6c2df32c2f1763dae85f8d40cbcc7ebada0cad38412d6f2f89fc1594a10077"
}
